### ISSUE TITLE
Missing Camera Raw Filter

### ISSUE THREAD

**Issue by LovelinMangang** [Gictorbit/photoshopCClinux#10]
This package is missing Camera Raw filter I try to open it from **Edit >>Preferences >> Camera Raw** then error messages like this

![Screenshot from 2020-05-08 20-58-56](https://user-images.githubusercontent.com/56713851/81421671-734c5080-916f-11ea-92a7-0c4965558f41.png)

My Distro is ubuntu 20.04

**Comment by Gictorbit** [comment]
thanks for your report
since `camera raw` is separate software, you must install it separately
so I added a new installer script for `adobe camera raw v12` [my latest commit](https://github.com/Gictorbit/photoshopCClinux/commit/15f702e479dbe4c77b5992554c9e44e8dd66cb3a)
>NOTE: since `camera raw` uses graphic card, make sure your graphic card driver is already installed and is configured correctly
