### ISSUE TITLE
Can't do anything once I load into PS

### ISSUE THREAD

**Issue by GarrettRector** [Gictorbit/photoshopCClinux#101]
**Describe the bug**
PS just doesn't load. I leave it for an hour and its stuck.

**linux Distribution (please complete the following information):**
 - Distro: Pop! Os
 - Desktop Environment: Gnome
 - gpu: Intel integrated graphics (Yes yes i know not the greatest but photoshop ran fine on this laptop on windows)

**Additional context**
Screen is just black and if I click on file to try to create a new file it just does nothing

**Screenshots**
![Screenshot from 2021-04-01 14-15-40](https://user-images.githubusercontent.com/80281078/113336861-f9780500-92f4-11eb-89a4-eaab90f33d84.png)

**Comment by GarrettRector** [comment]
FYI - idk why it put an installer script bug. I didn't specify that

**Comment by LanThrusteR** [comment]
Press Ctrl + K then go to General, switch off Show Start workspace when no Documents are Open and then then turn on use Legacy New Document

If that didn't fix the problem, then go to wine backtrace  you're likely having problems with the overrides namely HTML rendering engine/gdiplus or wine

you would need these overrides for CS18 to work properly

REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\AppDefaults\PhotoshopSE.exe]

[HKEY_CURRENT_USER\Software\Wine\AppDefaults\PhotoshopSE.exe\DllOverrides]
"api-ms-win-core-console-l1-1-0"="native,builtin"
"api-ms-win-core-datetime-l1-1-0"="native,builtin"
"api-ms-win-core-debug-l1-1-0"="native,builtin"
"api-ms-win-core-errorhandling-l1-1-0"="native,builtin"
"api-ms-win-core-file-l1-1-0"="native,builtin"
"api-ms-win-core-file-l1-2-0"="native,builtin"
"api-ms-win-core-file-l2-1-0"="native,builtin"
"api-ms-win-core-handle-l1-1-0"="native,builtin"
"api-ms-win-core-heap-l1-1-0"="native,builtin"
"api-ms-win-core-interlocked-l1-1-0"="native,builtin"
"api-ms-win-core-libraryloader-l1-1-0"="native,builtin"
"api-ms-win-core-localization-l1-2-0"="native,builtin"
"api-ms-win-core-memory-l1-1-0"="native,builtin"
"api-ms-win-core-namedpipe-l1-1-0"="native,builtin"
"api-ms-win-core-processenvironment-"="native,builtin"
"api-ms-win-core-processthreads-l1-1-"="native,builtin"
"api-ms-win-core-profile-l1-1-0"="native,builtin"
"api-ms-win-core-string-l1-1-0"="native,builtin"
"api-ms-win-core-synch-l1-1-0"="native,builtin"
"api-ms-win-core-synch-l1-2-0"="native,builtin"
"api-ms-win-core-sysinfo-l1-1-0"="native,builtin"
"api-ms-win-core-timezone-l1-1-0"="native,builtin"
"api-ms-win-core-util-l1-1-0"="native,builtin"
"api-ms-win-crt-conio-l1-1-0"="native,builtin"
"api-ms-win-crt-convert-l1-1-0"="native,builtin"
"api-ms-win-crt-environment-l1-1-0"="native,builtin"
"api-ms-win-crt-filesystem-l1-1-0"="native,builtin"
"api-ms-win-crt-heap-l1-1-0"="native,builtin"
"api-ms-win-crt-locale-l1-1-0"="native,builtin"
"api-ms-win-crt-math-l1-1-0"="native,builtin"
"api-ms-win-crt-multibyte-l1-1-0"="native,builtin"
"api-ms-win-crt-runtime-l1-1-0"="native,builtin"
"api-ms-win-crt-stdio-l1-1-0"="native,builtin"
"api-ms-win-crt-string-l1-1-0"="native,builtin"
"api-ms-win-crt-time-l1-1-0"="native,builtin"
"api-ms-win-crt-utility-l1-1-0"="native,builtin"
"atmlib"="native,builtin"
"d3d10_1"="native,builtin"
"d3d10_1core"="native,builtin"
"d3d10level9"="native,builtin"
"d3d10warp"="native,builtin"
"d3d11"="native,builtin"
"d3d9"="native,builtin"
"dxgi"="native,builtin"
"gdiplus"="native,builtin"
"msvcp120"="native,builtin"
"msvcp140"="native,builtin"
"msvcp90"="native,builtin"
"msvcr120"="native,builtin"
"ucrtbase"="native,builtin"
"vcruntime140"="native,builtin"

**Comment by LanThrusteR** [comment]
My guess - because he forgot to turn off Show "Start Workspace When Documents are Open" and turn on use Legacy "New Document" interface at setup time.

**Comment by GarrettRector** [comment]
The legacy new document worked perfectly, thanks!
