### ISSUE TITLE
Error: user.reg not found :(

### ISSUE THREAD

**Issue by hmmanshh** [Gictorbit/photoshopCClinux#108]
Every time I try running the ./setup script, I go to the winecfg and then I get this error which I cannot find a fix for.

_wine variables exported...
please install mono and gecko packages then click on OK button, do not change Windows version from Windows 7
prefix configured...
error: user.reg Not Found :(_

I tried trashing the ~/.wine, but nothing seems to work.
It would be great to get help

**Comment by PoorPocketsMcNewHold** [comment]
By ¨commented out¨, This mean commenting out that part of the `scripts/PhotoshopSetup.sh`: 
```bash
    if [ -f "$WINE_PREFIX/user.reg" ];then
        add dark mod
        set_dark_mod
    else
        error "user.reg Not Found :("
    fi
```

**Comment by ZombieVaccine** [comment]
This solution worked for me. Thank you!

**Comment by RedBadCommander** [comment]
For me to.
Thank You Guys

**Comment by Bricks666** [comment]
I fixed this to make it work completely by writing the absolute path to the user.reg file
`    if [ -f "/home/${userName}/.wine/user.reg" ];then
        #add dark mod
        set_dark_mod
    else
        error "user.reg Not Found :("
    fi
`
