### ISSUE TITLE
First Start / Initializing Dial... Wine Error

### ISSUE THREAD

**Issue by Pr1maX** [Gictorbit/photoshopCClinux#110]
**Describe the bug**

**linux Distribution (please complete the following information):**
Linux Mint 20.1 x64

**Additional context**
Error Log: https://pastebin.com/qGEBg4BC

**Screenshots**
![Bildschirmfoto vom 2021-04-20 18-09-54](https://user-images.githubusercontent.com/16181804/115429512-c3e37f00-a203-11eb-916c-21fdc729e9d1.png)

**Comment by mehmetext** [comment]
Same error for me...
