### ISSUE TITLE
Bash process

### ISSUE THREAD

**Issue by m4shuu** [Gictorbit/photoshopCClinux#112]
![image](https://user-images.githubusercontent.com/71311924/116530429-9936ac00-a910-11eb-93c8-91d29403f18b.png)

A noob question, but what does this process do? I always see a process named **bash**, with the logo of photoshop in system monitor . It appears in there without even having it opened yet.

**Comment by Gictorbit** [comment]
When you open Photoshop, the desktop entry will run `launcher.sh` which is a bash script for example:

![image](https://user-images.githubusercontent.com/34630603/116537175-21aa5200-a8fb-11eb-8f6d-2c37fc51c26f.png)
and when you close the photoshop it's process will end
