### ISSUE TITLE
warning: sha256sum mismatch! 

### ISSUE THREAD

**Issue by ruhend** [Gictorbit/photoshopCClinux#115]
warning: sha256sum mismatch! Rename /home/chocoflojo/.cache/winetricks/vcrun2008/vcredist_x86.exe and try again.

Possible problem root: WInetricks
Steps tried: building winetricks from source
           manual installation

Linux Distro : Manjaro Unstable
DE: Gnome-40.1
GPU: Intel UHD620
Display Server: X11 as well as Wayland

![image](https://user-images.githubusercontent.com/54891285/118449410-c062eb00-b710-11eb-866a-ad55b014064c.png)

Later it continues downloading the photoshop package (.tgz)

**Comment by ruhend** [comment]
Looks like the issue was with the winetricks.
Replacing the sha256sum in /usr/bin/winetricks solved the issue for me.

**Comment by chiiglaaa** [comment]
i have same problem cant find solution :| im using Linux mint 21

**Comment by mitchellkrogza** [comment]
```sudo winetricks --self-update``` solved this for me
