### ISSUE TITLE
Pressure sensitivity does not work

### ISSUE THREAD

**Issue by pserey** [Gictorbit/photoshopCClinux#15]
Installation and program runned perfectly. Sadly, I cant do my entire workflow because it wont recognize my wacom tablet pressure sensibility.

**Comment by PaulCoolDQueenLeon** [comment]
Heya! I found a way to make it work!
Install the OpenTabletDriver, make all the stuff for recognize your tablet, then make it as relative mode, this worked for me, but sometimes it just stop working and I need to restart the Photoshop or make it as another mode and change to relative again.
If this don't work make the thing of Photoshop stop using the Windows Ink or install the Windows Ink in the Plugins Manager of OpenTabletDriver.
I don't know if this will work for everyone, and I didn't saw anyone saying about that as well, so yeah... ._;
Good luck and have fun painting/drawing using Photoshop! Ty~~

**Comment by pserey** [comment]
Nice!!! I wanted to tell you sometime ago that it seemed to work randomly in my PC (?). Like, I was scribbling arround and sometimes the software recognized the pressure sensitivity haha

I think now that you have found a way to recognize it more stably it might work really well! I'll give it a try in a minute and give you feedback!

**Comment by Gictorbit** [comment]
hi thanks for sharing your experience. Actually, I haven't any Wacom tablet to test this, and I don't know how to fix these issues right now.good luck

**Comment by pserey** [comment]
If I have any way of helping in this, I'll be happy to! I'm a constant user of the Adobe suite and other software that don't have linux support event though I prefer working on a Unix based environment. This type of project is what this community needs!

**Comment by possibly-not** [comment]
It's so close!! Unfortunately I'm really struggling with consistency with the OpenTabletDriver like @pserey , even with the Windows Ink mode. About half the time each line only connects the first point and last point of a brush stroke. The other half it works! But also half the time pressure isn't recognised and half the time it is... as well there are also some really jagged lines at times (very spikey circles...) But when it works for one brush stroke, pressure works perfectly! I'm fairly confident this is on Wine somewhere down the line, as the tablet visualiser worked great and its nice and smooth.

I recommend to give https://krita.org/en/ a try. There are options for tablets in the settings. Unfortunately I had some troubles there as well with clicking but that's for another day...
