### ISSUE TITLE
Mask editing error.

### ISSUE THREAD

**Issue by Dzheremi2** [Gictorbit/photoshopCClinux#155]
**Describe the bug**
When I tries to edit mask settings and press OK button, change not applying and mask editors closing with this error: Could not complete your request because of a programm error. 

**Linux Distribution:**
 - Distro: Ubuntu 21.10
 - Desktop Environment: GNOME 40.5
 - gpu: AMD ATI Radeon R2/R3/R4/R5 Graphics
 - display server: Wayland

**Screenshots**
![Снимок экрана от 2022-02-04 12-42-48](https://user-images.githubusercontent.com/46569046/152507434-86cd0c5b-1431-449b-9ecb-88a0bbf889f6.png)

**Comment by CSMarckitus** [comment]
Hello @Dzheremi-belpois  , I honestly don't know what your mistake could be. Some time ago I created a different installer than Gictorbit with the latest version of Photoshop 2021 and it has worked well for many people, if you want to try it to see if it works for you: https://github.com/CSMarckitus/Photoshop.
Any questions I'll be here!
