### ISSUE TITLE
Not supporting graphic tablet

### ISSUE THREAD

**Issue by Borjimi1** [Gictorbit/photoshopCClinux#16]
Hi there! I'm using xp pen official drivers for my tablet. Its works fine in other apps, but in this photoshop pressure sens is not work at all. P.S. tablets buttons works fine
any advise? :)

**Comment by Gictorbit** [comment]
hi thank's for testing this script
this is similar to 7th issue read #7 
as I said before, the installer script uses `wine` in the background to run photoshop which is a `windows` simulator. so obviously it depends on pressure pens driver support.
I haven't a pressure pen right now to test and fix this but I think if we install windows driver of pressure pen it could work.
can you send me your driver? I will add a driver installer script then you can test it

**Comment by Borjimi1** [comment]
Sorry, I saw those posts after I created this one.
I agree about win drivers. I even tried to install the win version using wine, but it didn't want to work...(
So this is Linux version driver : https://www.xp-pen.com/download-299.html (go down and you will see linux version)

**Comment by Borjimi1** [comment]
hey! How its going?

**Comment by Gictorbit** [comment]
hi sorry I was busy.
I tested driver installation and it doesn't work, seems we haven't pen pressure support in wine yet :disappointed:

**Comment by Borjimi1** [comment]
Its ok. Dont worry about it :)
In this 9 days I tried a lot of things and became at same thing: wine dont support pen pressure which is  painful(
Anyway thanks for answering and have a good day!

**Comment by PaulCoolDQueenLeon** [comment]
I do have a Wacom Intuos Comic Tablet and the same thing is happening to me, the pressure is not working correctly

**Comment by PaulCoolDQueenLeon** [comment]
Heya! I found a way to make it work! 
 Install the OpenTabletDriver, make all the stuff for recognize your tablet, then make it as relative mode, this worked for me, but sometimes it just stop working and I need to restart the Photoshop or make it as another mode and change to relative again.
 If this don't work make the thing of Photoshop stop using the Windows Ink or install the Windows Ink in the Plugins Manager of OpenTabletDriver.
 I don't know if this will work for everyone, and I didn't saw anyone saying about that as well, so yeah... ._; 
 Good luck and have fun painting/drawing using Photoshop! Ty~~
