### ISSUE TITLE
Unable to find a way to make photoshop run with accelerated grafics.

### ISSUE THREAD

**Issue by No-Biggie805** [Gictorbit/photoshopCClinux#160]
Hi, 
so basically i’ve trying to set photoshopCC running with accelerated grafics in order to make it a more sophisticated workload, based on my researsh it must be around the .dll files stored inside of wine, but some of the ones pointed at https://github.com/Gictorbit/photoshopCClinux/issues/103 like d3d10level9.dll and d3d10warp.dll are not found, also on winetricks i just can’t find them, thus i am running through some difficulties that way, because i am unable to set it on 32bit, if needed then i reenstall the distro.
I don’t think that drivers of my grafics card are missing as thus i even instaled mesa and lib32 i think though i could be also very wrong on that. 
So yeah it might be a bit of trivial matter but i am new to wine, and a noob at linux overall so my apology, also maybe to help i leave my SO/hardware specs.

-  OS: Zorin 16 lite, xfce desktop, x86_64bit version;

 device: MacBook pro 2011;	
 cpu: i7-2620m;
 gpu: intel hd3000;
 memory: 4GB;

I don't mind to anwser any question,
any help is much apreciated.

**Comment by rumplin** [comment]
Try to read trough this https://sudonull.com/post/6539-Turn-on-GPU-acceleration-in-Photoshop-for-Wine
Be aware that the article is a bit outdated, so you might want to google which repository to add for your hardware.

Some suggest `mesa-utils` or `xserver-xorg-video-intel`

**Comment by No-Biggie805** [comment]
> Try to read trough this https://sudonull.com/post/6539-Turn-on-GPU-acceleration-in-Photoshop-for-Wine Be aware that the article is a bit outdated, so you might want to google which repository to add for your hardware.
> 
> Some suggest `mesa-utils` or `xserver-xorg-video-intel`

Thank you for the help but i did not install the repo correctly at the time.. so my bad also. The article you shared really is outdated because the repository shown in there no longer exists.. 
Thanks anyways, i'll be closing then. 
Still might ever be useful in the future since i'd really like to use wine more for running windows apps.
