### ISSUE TITLE
Changing eraser size logs out of linux session

### ISSUE THREAD

**Issue by betafcc** [Gictorbit/photoshopCClinux#17]
On linux mint 19.1 Tessa, nvidia optimus graphics, installing normally as per the instructions, if I try to change the brush size, either by 'right click -> drag slider' or by 'alt + right mouse drag', when the dialog box closes, the linux session logs out. Any idea why?

**Comment by Gictorbit** [comment]
uninstall photoshop and install it again with the 2nd method. it's more compatible this could fix some issue.
and give me feedback

**Comment by betafcc** [comment]
Thank you @Gictorbit, that worked
