### ISSUE TITLE
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2) [solved]

### ISSUE THREAD

**Issue by RuiMinamino07** [Gictorbit/photoshopCClinux#172]
![Screenshot from 2022-05-21 09-49-43](https://user-images.githubusercontent.com/105979440/169654642-0a5b22a7-c769-4732-9adb-b0e588dd2298.png)

It's fine in the Illustrator version but here in Photoshop, at some point I always get this one when I'm in either debian or arch. In Ubuntu, it works smoothly. Thanks for any help in advance

P.S. UPDATE: I ALREADY SOLVE MY ISSUE. I DON'T KNOW EXACTLY IF SERVER ISSUE OR INTERNET ISSUE BUT WHEN I RETRY DOING IT BY MORNING THIS DAY, I NOTICE THAT THE PERCENT DIDN'T STOP AND EVERYTHING FLOWS SMOOTHLY COMPARE TO YESTERDAY. IF EVER I WOULD SUGGEST TO OTHERS WHO WILL TRY THIS TO TRY DOWNLOADING THE SOURCE IF IT WILL NOT PAUSE IN NORMAL DOWNLOAD. IF SO, THEN IT MIGHT PROCEED SMOOTHLY HERE AS WELL.

**Comment by g-savitha** [comment]
So is it internet issue then?
