### ISSUE TITLE
error: sorry something went wrong during photoshop installation

### ISSUE THREAD

**Issue by DashReza7** [Gictorbit/photoshopCClinux#174]
Hello. when I try to install photoshop using the script, it gives me this error
"error: sorry something went wrong during photoshop installation"
it has downloaded required files (about 1GB).
also I have wine, wine64 and winetricks installed

the annoying thing is that I don't get any information from error why this happens

**Information**
 - Distro: Ubuntu 20.04
 - Desktop Environment: Gnome
 - gpu: nvidia Geforce 930 MX
 - display server: Xorg

**Comment by albakhtari** [comment]
This repo has been obsolete for almost a year now, I wrote a [new script](https://github.com/YoungFellow-le/Ps-22-Linux) that installs Adobe Photoshop CC 2021, you might want to check that out.
