### ISSUE TITLE
Error CURL Download

### ISSUE THREAD

**Issue by neemiaslryu** [Gictorbit/photoshopCClinux#180]
**Describe the bug**
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

**Explain Bug**
        when I tried to install through this script, I always came across an error        
        when downloading the file via curl , this is due to multiple server crashes of the hosted file.
        most often for installation

**My Machine Config**

        OS: Garuda Linux x86_64
        Kernel: 5.18.16-zen1-1-zen
        Uptime: 4 hours, 3 mins
        Packages: 1915 (pacman)[stable]
        Shell: fish 3.5.1
        Resolution: 1366x768
        Resolution: 1920x1080
        WM: KWin (X11)
        WM Theme: Sweet-Dark
        Theme:  [Plasma], {?}Sweet-Dark [GTK2/3/4]
        Icons: BeautyLine [GTK2/3/4]
        Terminal: konsole
        Terminal Font: FiraCode Nerd Font Mono 12
        CPU: Intel Core i5-9400F (6) @ 4.1GHz
        GPU: Nvidia GeForce GTX 750 Ti
        Memory: 5920MiB / 7868MiB

**Comment by sdasrc** [comment]
Getting the same bug
```
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
md5 is not match
```
Any fixes so far?

**Comment by sdasrc** [comment]
Found a solution. The download link in curl stops working after a minute or so. I downloaded it manually on the browser (URL : https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz).

After that I went to `photoshopCClinux/scripts/`, edited the function `install_photoshopSE()` in `PhotoshopSetup.sh` to include the location of the now local installation file. I commented out the line where the setup file gets downloaded. This worked.

```
function install_photoshopSE() {
    local filename="photoshopCC-V19.1.6-2018x64.tgz"
    local filemd5="b63f6ed690343ee12b6195424f94c33f"
    local filelink="https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz"
    # local filelink="http://127.0.0.1:8080/photoshopCC-V19.1.6-2018x64.tgz"
    local filepath="<<FULL PATH TO DOWNLOADED FILE>>"

    # download_component $filepath $filemd5 $filelink $filename

    mkdir "$RESOURCES_PATH/photoshopCC"
    show_message "extract photoshop..."
    tar -xzf "$filepath" -C "$RESOURCES_PATH/photoshopCC"
```

**Comment by samuk10** [comment]
What worked for me:

download the file with support resume:

     $ wget -c https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz


edit:

     $ vim photoshopCClinux/scripts/PhotoshopSetup.sh

find the function:

function install_photoshopSE() {

    # COMENT THIS
    #local filelink="https://victor.poshtiban.io/p/gictor/photoshopCC/photoshop>
    # ADD THIS LINE
    local filelink="http://127.0.0.1:8000/photoshopCC-V19.1.6-2018x64.tgz"

then run your local server:

    python3 -m http.server -d .

chmod +x setup.sh
./setup.sh

follow the rest

**Comment by neemiaslryu** [comment]
> What worked for me:
> 
> download the file with support resume:
> 
> ```
>  $ wget -c https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz
> ```
> 
> edit:
> 
> ```
>  $ vim photoshopCClinux/scripts/PhotoshopSetup.sh
> ```
> 
> find the function:
> 
> function install_photoshopSE() {
> 
> ```
> # COMENT THIS
> #local filelink="https://victor.poshtiban.io/p/gictor/photoshopCC/photoshop>
> # ADD THIS LINE
> local filelink="http://127.0.0.1:8000/photoshopCC-V19.1.6-2018x64.tgz"
> ```
> 
> then run your local server:
> 
> ```
> python3 -m http.server -d .
> ```
> 
> chmod +x setup.sh ./setup.sh
> 
> follow the rest

thank you so much

a quick fix

 **_I forced the download via Wget_**

Editing the code
/scripts/SharedFuncs.sh

coment lines

**184** #ariapkg=$(package_installed aria2c "summary")
**185** #curlpkg=$(package_installed curl "summary")

**this will force the condition ato return = false (lines 187 and 195), then it will accept the condition to Download with Wget (line 198)

**187** if [ "$ariapkg" == "true" ];then .....
