### ISSUE TITLE
download failed 

### ISSUE THREAD

**Issue by Dark6273** [Gictorbit/photoshopCClinux#186]
**Describe the bug**

**linux Distribution (please complete the following information):**
 - Distro: ubuntu
 - Desktop Environment: gnome
 - gpu: [model of your graphics card on your Laptop powered by Linux e.g. intel,Nvidia,and] you can check with command lspci | grep -i --color 'vga\|3d\|2d'
 - display server: wayland

**Additional context**

**Screenshots**
![Screenshot from 2022-09-29 09-57-18](https://user-images.githubusercontent.com/68940369/192955384-d9a6bcb0-5908-4c2d-90ea-0db6e42db00e.png)

**Comment by Dark6273** [comment]
Found a solution. The download link in curl stops working after a minute or so. I downloaded it manually on the browser (URL : https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz).

After that I went to photoshopCClinux/scripts/, edited the function install_photoshopSE() in PhotoshopSetup.sh to include the location of the now local installation file. I commented out the line where the setup file gets downloaded. This worked.

```
  function install_photoshopSE() {
      local filename="photoshopCC-V19.1.6-2018x64.tgz"
      local filemd5="b63f6ed690343ee12b6195424f94c33f"
      local filelink="https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz"
      # local filelink="http://127.0.0.1:8080/photoshopCC-V19.1.6-2018x64.tgz"
      local filepath="<<FULL PATH TO DOWNLOADED FILE>>"
  
      # download_component $filepath $filemd5 $filelink $filename
  
      mkdir "$RESOURCES_PATH/photoshopCC"
      show_message "extract photoshop..."
      tar -xzf "$filepath" -C "$RESOURCES_PATH/photoshopCC"
```

**Comment by fedehc** [comment]
> Found a solution. The download link in curl stops working after a minute or so. I downloaded it manually on the browser (URL : https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz).
> 
Unfortunately that link does not work anymore and the download problem still persists. But here are another couple of links that still work:
https://github.com/Gictorbit/photoshopCClinux/issues/40#issuecomment-667716142
