### ISSUE TITLE
pacman -Syy shouldn't be run. 

### ISSUE THREAD

**Issue by tpurde** [Gictorbit/photoshopCClinux#20]
You recommended people to run this command in the README.md file. `sudo pacman -Syy wine aria2`
You shouldn't run Sy or Syy without the u. The command should be `sudo pacman -Syu wine aria2`
I'd love it if you fix this, because this can lead up to problems on Arch Linux machines.

**Comment by Gictorbit** [comment]
thank you I fixed it
