### ISSUE TITLE
Installed but wine gives an issue here is the log.

### ISSUE THREAD

**Issue by EnriLion** [Gictorbit/photoshopCClinux#201]
Unhandled exception: page fault on read access to 0x00000000 in 64-bit code (0x000000006872cb85).
Register dump:
 rip:000000006872cb85 rsp:000000000021d100 rbp:000000000021d230 eflags:00010286 (  R- --  I S - -P- )
 rax:0000000000000000 rbx:000000000021d1a8 rcx:ffffffffffffffff rdx:0000000000000000
 rsi:00007fffffb9fc20 rdi:0000000000000000  r8:0000000005eddb20  r9:0000000000000028 r10:0000000000000000
 r11:0000000005eddb20 r12:0000000000000000 r13:0000000008a58aa8 r14:0000000005479e10 r15:0000000000000000
Stack dump:
0x000000000021d100:  0000000005eddb20 0000000000000028
0x000000000021d110:  0000000005eddb20 0000000008a555f0
0x000000000021d120:  0000000008a55b70 0000000003bcfa60
0x000000000021d130:  0000000005eddb20 0000000000000000
0x000000000021d140:  00007fffffb9fc20 0000000000000000
0x000000000021d150:  0000000000000002 0000000000000000
0x000000000021d160:  fffffffffffffffe 0000000000000000
0x000000000021d170:  00007fffffb9fc20 fffffffffffffffe
0x000000000021d180:  000000006898b1f0 00000000687c7c79
0x000000000021d190:  00007fffffb9fc20 000000006898b170
0x000000000021d1a0:  0000000000000000 0000000000000000
0x000000000021d1b0:  fffffffffffffffe 0000000000000000
Backtrace:
=>0 0x000000006872cb85 EntryPoint+0xffffffffffffffff() in dvacore (0x000000000021d230)
0x000000006872cb85 EntryPoint+0xffffffffffffffff in dvacore: repne scasw	(%rsi)
Modules:
Module	Address					Debug info	Name (114 modules)
PE	          220000-          288000	Deferred        bib
PE	          290000-          2e0000	Deferred        bibutils
PE	          2e0000-          354000	Deferred        adobexmp
PE	          360000-          3cf000	Deferred        are
PE	          3d0000-          3e2000	Deferred        adobesplashkit
PE	          400000-         2268000	Deferred        illustrator
PE	         2270000-         2a4c000	Deferred        agm
PE	         2a50000-         2e97000	Deferred        cooltype
PE	         2ea0000-         3430000	Deferred        mps
PE	         3430000-         3605000	Deferred        ace
PE	         3610000-         372d000	Deferred        adobexmpfiles
PE	         3730000-         389b000	Deferred        wrservices
PE	         38a0000-         3a3b000	Deferred        adobelinguistic
PE	         3a40000-         3b70000	Deferred        icuuc40
PE	         3b70000-         42e0000	Deferred        dvaui
PE	         42e0000-         4631000	Deferred        dvaai
PE	         4640000-         473f000	Deferred        boost_regex
PE	         4740000-         48d1000	Deferred        exo
PE	         48e0000-         4b14000	Deferred        adobeowl
PE	         4b20000-         4b55000	Deferred        axe8sharedexpat
PE	         4b60000-         4dbb000	Deferred        amtlib
PE	         4dc0000-         4e0f000	Deferred        ahclient
PE	         4e10000-         4e2a000	Deferred        alcid
PE	         62c0000-         6498000	Deferred        aires
PE	         6c50000-         6dd1000	Deferred        imslib
PE	         b620000-         b828000	Deferred        adobehunspellplugin
PE	         b830000-         b938000	Deferred        wrliloplugin
PE	         b940000-         ba25000	Deferred        aiport
PE	         ba30000-         c314000	Deferred        adobepdfl
PE	         c320000-         c404000	Deferred        jp2klib
PE	         c410000-         c4ca000	Deferred        filterport
PE	         c4d0000-         c61e000	Deferred        pdfport
PE	        10000000-        100eb000	Deferred        axedomcore
PE	        4a900000-        4aa50000	Deferred        icuin40
PE	        4ad00000-        4ba47000	Deferred        icudt40
PE	        60600000-        60618000	Deferred        action.aip
PE	        60620000-        6079b000	Deferred        action panel.aip
PE	        60af0000-        60b03000	Deferred        artconverters.aip
PE	        60dc0000-        60f0a000	Deferred        beautifulstrokes.aip
PE	        60fe0000-        61032000	Deferred        pencil tool.aip
PE	        61090000-        610ba000	Deferred        brushmanager.aip
PE	        613f0000-        61585000	Deferred        colorharmony.aip
PE	        615e0000-        61644000	Deferred        controlpanel.aip
PE	        62540000-        62553000	Deferred        flatten transparency.aip
PE	        62600000-        62680000	Deferred        foconversionsuite.aip
PE	        62680000-        62698000	Deferred        fwserver.aip
PE	        63c80000-        63cc7000	Deferred        pathfinder suite.aip
PE	        63f10000-        64014000	Deferred        pdfsuite.aip
PE	        641c0000-        6425e000	Deferred        photoshop adapter.aip
PE	        64b00000-        64b48000	Deferred        rasterize.aip
PE	        65fb0000-        66037000	Deferred        slicing.aip
PE	        66fe0000-        671ec000	Deferred        userinterface.aip
PE	        67c80000-        67cbe000	Deferred        boost_filesystem
PE	        67db0000-        67dc8000	Deferred        boost_threads
PE	        67ea0000-        67ebd000	Deferred        boost_signals
PE	        67ec0000-        67ecc000	Deferred        boost_system
PE	        67ed0000-        67ee8000	Deferred        boost_date_time
PE	        67ef0000-        683af000	Deferred        dvaadameve
PE	        686f0000-        689dc000	Export          dvacore
PE	        69070000-        691cb000	Deferred        dvaworkspace
PE	        69330000-        69339000	Deferred        spbasic
PE	        7a850000-        7a854000	Deferred        opengl32
PE	        7b000000-        7b3fd000	Deferred        kernelbase
PE	        7b600000-        7b969000	Deferred        kernel32
PE	        7bc00000-        7bf3c000	Deferred        ntdll
PE	       180000000-       18005f000	Deferred        logsession
PE	       1c8db0000-       1c9097000	Deferred        msvcrt
PE	       1d0830000-       1d0d57000	Deferred        actxprxy
PE	       21a7e0000-       21a9ce000	Deferred        setupapi
PE	       21f7f0000-       21f8aa000	Deferred        msvcp100
PE	       228450000-       2284c4000	Deferred        propsys
PE	       231ae0000-       231d60000	Deferred        rpcrt4
PE	       23d820000-       23dfc2000	Deferred        user32
PE	       2419a0000-       241b0c000	Deferred        wbemprox
PE	       241b90000-       241bb9000	Deferred        zlib1
PE	       243540000-       24382e000	Deferred        gdiplus
PE	       24f470000-       24f4d5000	Deferred        mpr
PE	       25d740000-       25d75f000	Deferred        dwmapi
PE	       26b4c0000-       26bbb9000	Deferred        gdi32
PE	       2739c0000-       273ec9000	Deferred        oleaut32
PE	       292520000-       292571000	Deferred        netprofm
PE	       2a4090000-       2a40bf000	Deferred        wtsapi32
PE	       2bb750000-       2bbcd8000	Deferred        comctl32
PE	       2e3540000-       2e364f000	Deferred        shlwapi
PE	       2e8f10000-       2e948f000	Deferred        ole32
PE	       2f1fa0000-       2f1fbe000	Deferred        version
PE	       2f7230000-       2f72d4000	Deferred        uxtheme
PE	       3126f0000-       312744000	Deferred        shcore
PE	       316370000-       316382000	Deferred        psapi
PE	       31f800000-       31fa8e000	Deferred        comdlg32
PE	       327020000-       3271a4000	Deferred        combase
PE	       329ba0000-       329c7f000	Deferred        msvcr100
PE	       32a700000-       32a7bc000	Deferred        sechost
PE	       32f9a0000-       32f9b7000	Deferred        msimg32
PE	       330260000-       330387000	Deferred        advapi32
PE	       346ba0000-       346bea000	Deferred        jsproxy
PE	       358120000-       35825c000	Deferred        winhttp
PE	       361860000-       361c6f000	Deferred        windowscodecs
PE	       3a0440000-       3a0691000	Deferred        wininet
PE	       3af670000-       3af9dd000	Deferred        ucrtbase
PE	       3afd00000-       3afd62000	Deferred        imm32
PE	       3be590000-       3be802000	Deferred        dbghelp
PE	    7f48c4080000-    7f48c4083000	Deferred        dwrite
PE	    7f48c4500000-    7f48c4504000	Deferred        wined3d
PE	    7f48c4750000-    7f48c4754000	Deferred        dxgi
PE	    7f48c5050000-    7f48c5054000	Deferred        winex11
PE	    7f48c5280000-    7f48c5283000	Deferred        kerberos
PE	    7f48c5b60000-    7f48c5b6b000	Deferred        winspool
PE	    7f48c5be0000-    7f48c64b2000	Deferred        shell32
PE	    7f48c65f0000-    7f48c65f4000	Deferred        dnsapi
PE	    7f48c6620000-    7f48c6626000	Deferred        ws2_32
PE	    7f48c6660000-    7f48c6664000	Deferred        iphlpapi
PE	    7f48c6690000-    7f48c6693000	Deferred        netapi32
PE	    7f48c67d0000-    7f48c67d3000	Deferred        secur32
Threads:
process  tid      prio (all id:s are in hex)
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	00000070    0
	00000088    0
	000000ac    0
	000000cc    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	0000005c    0
00000060 plugplay.exe
	00000064    0
	00000074    0
	00000078    0
	0000007c    0
	00000098    0
00000068 explorer.exe
	0000006c    0
	000000b8    0
	000000bc    0
00000080 winedevice.exe
	00000084    0
	0000008c    0
	00000090    0
	00000094    0
	000000a0    0
000000a4 svchost.exe
	000000a8    0
	000000b0    0
	000000b4    0
000000c4 rpcss.exe
	000000c8    0
	000000d4    0
	000000d8    0
	000000dc    0
	000000e0    0
	000000e4    0
	00000120    0
000000ec IllustratorCC64.exe
	000000f0    0
00000114 (D) Z:\home\leon\.illustratorCC17\IllustratorCC17\App\Illustrator64\Support Files\Contents\Windows\Illustrator.exe
	00000118    0 <==
	0000011c    0
	00000128    0
	0000012c    0
	00000138    0
System information:
    Wine build: wine-6.0.3 (Ubuntu 6.0.3~repack-1)
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 5.15.0-56-generic

**Comment by hockeymikey** [comment]
How'd you fix?
