### ISSUE TITLE
Can't finish downloading

### ISSUE THREAD

**Issue by vanTesselhof** [Gictorbit/photoshopCClinux#211]
I try to download it and it pops up with an error, that's not possible to download 'photoshopCC-V19.1.6-2018x64.tgz'. I can't find any logs where some information could be. Someone has similar problems about that?

```
`Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
c43163|ERR |       0B/s|/home/jakob/.cache/photoshopCCV19/photoshopCC-V19.1.6-2018x64.tgz

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
error: sorry something went wrong during download photoshopCC-V19.1.6-2018x64.tgz
`
```

Please reach out for further information!

**linux Distribution (please complete the following information):**
 - Distro: Linux Mint
 - Desktop Environment: [GNOME
 - gpu: Intel Corporation UHD Graphics 620
 - display server:

**Comment by rossw01** [comment]
Something similar(?) seems to be happening for me using Arch:

```
downloading photoshopCC-V19.1.6-2018x64.tgz ...
using curl to download photoshopCC-V19.1.6-2018x64.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (6) Could not resolve host: victor.poshtiban.io
error: sorry something went wrong during download photoshopCC-V19.1.6-2018x64.tgz
```

**Comment by rossw01** [comment]
@vanTesselhof 

After looking through other Issues, it seems it's happening for everyone. 

Try this:
1. [Download these files](https://github.com/Gictorbit/photoshopCClinux/issues/205#issuecomment-1754164730) and leave them in your Downloads folder.
2. Open ```photoshopCClinux/scripts/PhotoshopSetup.sh``` in any text editor.
3. Replace ```function replacement()``` and ```install_photoshopSE()``` with their [updated counterparts ](https://github.com/Gictorbit/photoshopCClinux/issues/205#issuecomment-1793879169).
4. Rerun ```setup.sh```.

**Comment by vanTesselhof** [comment]
I solved it through downloading the files [here](https://github.com/Gictorbit/photoshopCClinux/issues/205#issuecomment-1754164730)
And moved it to `~/.cache/photoshopCCV19` --> And then rerun the setup.sh file
Works just fine! :)
