### ISSUE TITLE
Installation in a different directory

### ISSUE THREAD

**Issue by iTzHard** [Gictorbit/photoshopCClinux#22]
Is there a way to use the script to setup the WINEPREFIX in somewhere that's not the home directory? I have a very small SSD and I can't afford to put Photoshop in it

**Comment by Gictorbit** [comment]
this is like #9 
you can use `-d` switch to specify installation path, and `-c` for the cache directory.
for example:
```bash
./PhotoshopSetupCustom.sh -d /mnt/myfiles/photoshop
or 
./PhotoshopSetup.sh -d /mnt/myfiles/photoshop -c /mnt/cache
```
if you don't use it, installer script uses the default path
also, uninstaller script and others will detect your custom path so there is no problem
I recommend just use `-d` argument and use default cache directory
this feature is under test after testing I'll add it to `setup.sh`
