### ISSUE TITLE
Not Running on Fedora

### ISSUE THREAD

**Issue by angeldanb** [Gictorbit/photoshopCClinux#23]
I installed wine and winetricks through the package installer and all worked well, the whole installation went through but when I open up photoshop, it loads and it just quits the program as if wasn't responding, it just disappears from the corner. The only repetitive error I saw through the terminal were 

<pre>You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
</pre>

and just some fixmes. Dont know what to do, any help?

**Comment by herosilas12** [comment]
what version of fedora are you using?
I am on 32 and it doesn't work at all ("wine config wine3.4 is invalid" errors)

**Comment by Gictorbit** [comment]
hi I made some changes and I disabled `64bit` limitation  you can try again on your `32bit` machine

**Comment by Gictorbit** [comment]
> You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> and just some fixmes. Dont know what to do, any help?

@angeldanb 
we have 2 installer script for ps installation wich one did you use? and what's your PC distro details?

**Comment by herosilas12** [comment]
I used stetup.sh on fedora 32 in a VM
