### ISSUE TITLE
Opening file associated images breaks ps

### ISSUE THREAD

**Issue by luni3359** [Gictorbit/photoshopCClinux#27]
After opening PS from a file that's been associated this message appears:
```
The Wine configuration in /home/user/.photoshopCCV19/prefix is being updated, please wait...
```
From then on trying to open PS from the ``photoshop`` command or with the shortcut always shows this error:

```
The program Photoshop.exe has encountered a serious problem and needs to close. We are sorry for the inconvenience.
```
PS can still open if you open files associated with the program, but not from ``launcher.sh``.

**Comment by luni3359** [comment]
Here's my association file (``wine-extension-psd.desktop``)
```
[Desktop Entry]
Type=Application
Name=Adobe Photoshop CC 2018
MimeType=image/vnd.adobe.photoshop;
Exec=env WINEPREFIX="/home/user/.photoshopCCV19/prefix" wine start /ProgIDOpen Photoshop.Image.19 %f
NoDisplay=true
StartupNotify=true
Icon=photoshop
```

**Comment by Gictorbit** [comment]
hi thanks for reporting this I checked that it works fine in my distro wich method did you use for installation?
`photoshopSetup.sh` or `photoshopSetupCustom.sh`?

**Comment by luni3359** [comment]
I used ``setup.sh`` and then pressed 1.

**Comment by luni3359** [comment]
I suppose that exporting these in the file association would fix everything

```bash
export WINEPREFIX="$WINE_PREFIX"
export PATH="$WINE_PATH/bin:$PATH"
export LD_LIBRARY_PATH="$WINE_PATH/lib:$LD_LIBRARY_PATH"
#export WINEDLLOVERRIDES="winemenubuilder.exe=d"
export WINESERVER="$WINE_PATH/bin/wineserver"
export WINELOADER="$WINE_PATH/bin/wine"
export WINEDLLPATH="$WINE_PATH/lib/wine"

wine "$SCR_PATH/prefix/drive_c/users/$USER/PhotoshopSE/Photoshop.exe"
```

I wanted to change the file association desktop file to something like...
```desktop
[Desktop Entry]
Type=Application
Name=Adobe Photoshop CC 2018
MimeType=image/vnd.adobe.photoshop;
Exec=bash /home/user/.photoshopCCV19/launcher/launcher.sh %f
NoDisplay=true
StartupNotify=true
Icon=photoshop
```

...but the script receives no parameters, and on top of that I don't know how to pass the file(s) from bash to wine (ps).

**Comment by fermmm** [comment]
Same problem here using Linux Mint. Did you manage to fix the issue?

**Comment by fermmm** [comment]
In a different computer also with Mint worked correctly, weird.. In this case the first time I opened photoshop I loaded a file and after that photoshop appeared on the applications suggestion list in "open with..." and just worked.

**Comment by Gictorbit** [comment]
I made some changes
can you try again?
There is no problem with this, based on latest changes
