### ISSUE TITLE
Cannot launch the application

### ISSUE THREAD

**Issue by imanoj997** [Gictorbit/photoshopCClinux#29]
**Describe the bug**
I installed the application and it worked fine. After a few days, I changed the photoshop icon in usr/share/icons (although I don't think this has anything to do with the issue). Now I cannot lunch the application when I click on the desktop icon nothing happens. Executing the laucher.sh file from terminal generates this error.

`wine: invalid directory pspath/prefix in WINEPREFIX: not an absolute path`

Here's the .desktop file

```
[Desktop Entry]
Encoding=UTF-8
Name=Photoshop CC
Exec=bash /home/imanoj997/.photoshopCCV19/launcher/launcher.sh
Type=Application
StartupNotify=true
Comment=Photoshop CC for Linux
Icon=photoshop
Name[fr_FR]=Photoshop CC
```

**linux Distribution (please complete the following information):**
 - Distro: [Ubuntu 20.04]
 - Desktop Environment: [Gnome]
 - Installation method:[2-photoshopSetupCustom.sh ]
 - gpu: [Nvdia mx 130]

**Comment by Gictorbit** [comment]
hi, what's the content of `launcher.sh`?
installer script configures `launcher.sh` during installation. I think you removed `launcher.sh` and replaced it with default script is that right?
uninstall photoshop and install it again it could solve the problem

**Comment by imanoj997** [comment]
Here's the content of launcher.sh, and no, I haven't removed the original; launcher.sh file.

`#!/usr/bin/env bash
if [ $# -ne 0 ];then
    echo "I have no parameters just run the script without arguments"
    exit 1
fi

notify-send "Photoshop CC started." -i "photoshop"

# SCR_PATH="$HOME/.photoshopCCV19"
# CACHE_PATH="$HOME/.cache/photoshopCCV19"
SCR_PATH="pspath"
CACHE_PATH="pscache"

WINE_PATH="$SCR_PATH/wine-3.4"

RESOURCES_PATH="$SCR_PATH/resources"
WINE_PREFIX="$SCR_PATH/prefix"
 

export WINEPREFIX="$WINE_PREFIX"
export PATH="$WINE_PATH/bin:$PATH"
export LD_LIBRARY_PATH="$WINE_PATH/lib:$LD_LIBRARY_PATH"
#export WINEDLLOVERRIDES="winemenubuilder.exe=d"
export WINESERVER="$WINE_PATH/bin/wineserver"
export WINELOADER="$WINE_PATH/bin/wine"
export WINEDLLPATH="$WINE_PATH/lib/wine"

wine "$SCR_PATH/prefix/drive_c/users/$USER/PhotoshopSE/Photoshop.exe"`

**Comment by Gictorbit** [comment]
installer script modifies the `launcher.sh`, so as you can see it doesn't modify yet which means the installer script even didn't run
anyway I made some changes please try again
