### ISSUE TITLE
No icon in photoshop.desktop

### ISSUE THREAD

**Issue by igoro00** [Gictorbit/photoshopCClinux#30]
**Describe the bug**
In the .desktop file icon is set to "photoshop" but my icon pack doesnt have that file. There is "application-photoshop"(which looks exactly like psd file icon....) but for example on Breeze neither of them are available.

I think the safest solution would be to check if "photoshop" icon is available and if not, add the default one to /usr/share/icons

**linux Distribution:**
 - Distro: Manjaro Linux
 - Desktop Environment: KDE
 - Installation method: both
 - gpu: RX 480 8GB w/ AMDGPU-PRO driver
 - display server: X11
 - Icons: Tela dark

**Screenshots**
![image](https://user-images.githubusercontent.com/35789870/87226421-e8b4e700-c393-11ea-8b7f-2c3b69df5d21.png)

**Comment by luni3359** [comment]
Does ``Icon=5C1F_Photoshop.0`` work for you? 
Anyway, any fallback icons should probably be in ``~/.local/share/icons/hicolor`` instead.

**Comment by igoro00** [comment]
Sorry, I can't check it rn. My fs somehow got corrupted after a power
loss(I used btrfs so I guess its kinda my fault) and I'm away from home for
the next week.

I'll check that when I come back home and reinstall my OS('cause who needs
backups? i dont xd) so don't close this issue

sob., 25 lip 2020, 08:08 użytkownik Luni <notifications@github.com> napisał:

**Comment by fermmm** [comment]
What worked for me is this:
1. Edit the file /usr/share/applications/Photoshop CC
2. Replace the Icon= line with this (replacing [user] for your user folder name):
Icon=/home/[user]/.local/share/icons/hicolor/256x256/apps/69C4_Photoshop.0.png

**Comment by luni3359** [comment]
> What worked for me is this:
> 
>     1. Edit the file /usr/share/applications/Photoshop CC
> 
>     2. Replace the Icon= line with this (replacing [user] for your user folder name):
>        Icon=/home/[user]/.local/share/icons/hicolor/256x256/apps/69C4_Photoshop.0.png

He should better edit the desktop file located in his own home folder, perhaps other users have different icon themes that work with ``photoshop``. By the way, any icons inside ``~/.local/share/icons/hicolor`` can be referenced by their filename alone, so ``Icon=69C4_Photoshop.0`` should be enough for you.

**Comment by fermmm** [comment]
> > What worked for me is this:
> > ```
> > 1. Edit the file /usr/share/applications/Photoshop CC
> > 
> > 2. Replace the Icon= line with this (replacing [user] for your user folder name):
> >    Icon=/home/[user]/.local/share/icons/hicolor/256x256/apps/69C4_Photoshop.0.png
> > ```
> 
> He should better edit the desktop file located in his own home folder, perhaps other users have different icon themes that work with `photoshop`. By the way, any icons inside `~/.local/share/icons/hicolor` can be referenced by their filename alone, so `Icon=69C4_Photoshop.0` should be enough for you.

For me it didn't work with just the file name.

**Comment by Gictorbit** [comment]
I fixed this issue
after installation, during launcher function it modifies `photoshop.desktop` and a photoshop icon as png will add to prefix
