### ISSUE TITLE
Camera raw crash photoshop

### ISSUE THREAD

**Issue by RiccardoDurante** [Gictorbit/photoshopCClinux#34]
When open camera raw a wine error message pop-up and photoshop crash

 - Distro: ArchLinux 5.7.8.1-1
 - Desktop Environment: Plasma KDE
 - Installation method: 1-photoshopSetup.sh and 3-install adobe camera raw
 - gpu: 00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
 - display server: X11

While installing photoshop appears this 2 errors but photoshop without open camera raw work perfect.

wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
Wine cannot find the ncurses library (libncurses.so.5).
0009:err:module:load_builtin_dll failed to load .so lib for builtin L"l3codeca.acm": libmpg123.so.0: cannot open shared object file: No such file or directory
downloading replacement.tgz ...

Here the wine error log after camera raw opened
LOG wine error: https://pastebin.com/X7ndXyFW

**Comment by hrqmonteiro** [comment]
I reported that in #32, and the dev didn't respond still.

**Comment by hrqmonteiro** [comment]
@Gictorbit you closed it but you still haven't responded on my issue?

**Comment by Gictorbit** [comment]
camera raw depends on GPU and wine should handle it this is `photoshop`/`wine` fault and I can't do anything unfortunately about it because photoshop is close source. you should consider that, photoshop performance on windows is greater than running photoshop on `wine` 
thanks

**Comment by hrqmonteiro** [comment]
I know photoshop performance on Windows is greater, since it is natively on windows...
But this is still a fault on the script, right? No other wine application i use, or game has ever crashed because of my gpu. The issue isn't cause of the graphics.

**Comment by hrqmonteiro** [comment]
If the script can't handle Camera Raw why do you have the option to install it? So..

**Comment by charlie39** [comment]
check this out 
https://github.com/Gictorbit/photoshopCClinux/issues/71#issuecomment-727240641

**Comment by grenvol** [comment]
@RiccardoDurante Your Pastebin link expired, can you repaste it please?

**Comment by RiccardoDurante** [comment]
> @RiccardoDurante Your Pastebin link expired, can you repaste it please?

Sorry, but I lost that pastebin
