### ISSUE TITLE
3D rendering unuseable slow, cant use liquify

### ISSUE THREAD

**Issue by thrdroom** [Gictorbit/photoshopCClinux#35]
**Describe the bug**
When i try to render a simple 3d object (white text), the process starts but it so extremely slow(1,5 hourse for 1 white 3d text) its unusable. Im pretty sure its not the fault of the GPU or the drivers, as i can run a uniengine render test and also a blender render just fine. It feels like GPU is not used for rendering, only CPU is fully utilized. "Use Graphics processor" is enabled in settings and photoshop detect the right GPU model correctly. I also can't use liquify.

**linux Distribution (please complete the following information):**
 - Distro: KDE NEON
 - Desktop Environment: KDE Plasma
 - Installation method: 1-photoshopSetup.sh AND 2-photoshopSetupCustom.sh. Tested both.
 - gpu: AMD Radeon RX 480
 - gpu-driver: amdgpu(default builtin open source driver)
 - display server: X11

**Screenshots**
I also get this error from time to time while using the programm.
![Screenshot_20200720_164111](https://user-images.githubusercontent.com/5912061/87955121-95d2e200-caad-11ea-9143-efb5da037fd8.png)

**Comment by xxSkyy** [comment]
Its partly fixable with disabling GPU acceleration. But it loses focus on liquify window and I had to alt+tab.

**Comment by thrdroom** [comment]
> Its partly fixable with disabling GPU acceleration. But it loses focus on liquify window and I had to alt+tab.

With "disabling GPU acceleration" you mean "preferences" > disable "Use Graphics processor"?
If so, i tried that and rendering 3D with CPU only gives me the same result > rendertimes of about 1,5 hours.

**Comment by xxSkyy** [comment]
I would want to use acceleration aswell but it doesnt work to me and disabling makes it sort of usable.

**Comment by luni3359** [comment]
Liquify just crashes on me and I'm on the same distro.

**Comment by xxSkyy** [comment]
> Liquify just crashes on me and I'm on the same distro.

If youre running on nvidia gpu update to nvidia-driver-450 and disable gpu acceleration in preformance settings on ps , all should be working now
