### ISSUE TITLE
Install scripts do not work in ZSH

### ISSUE THREAD

**Issue by thrdroom** [Gictorbit/photoshopCClinux#36]
Hi.
the install scripts  does not work in ZSH itself. They only work when called via bash.
Can we make this work on ZSH by default?

**Comment by telmotrooper** [comment]
That's weird, I'm using zsh and it installed just fine.

**Comment by thrdroom** [comment]
> That's weird, I'm using zsh and it installed just fine.

You are right. When i `cd scripts/` directory and call `./PhotoshopSetupCustom.sh -d ~/apps/photoshop` the script runs fine.
But when i try t call the script from the root of the gitrepo like `scripts/PhotoshopSetupCustom.sh -d ~/apps/photoshop` i get the errors.

So, the problem is not the facts that the script is executed in ZSH, but the fact that it hast to be executed withing the scripts-folder. Git readme should be more precise about this fact imho.

**Comment by RyanGamingXbox** [comment]
The script is never run in **ZSH**, it's common practise in _shell scripts_ to pick a shell before doing anything.
So the code `#!/bin/env bash` summons a **bash session** instead of a **ZSH hat the code uses other scripts in the same folder. Probably to save on space or something, we could easily fix it by putting all the code that it's trying to get into all shell scripts that mention `source`

**Comment by RyanGamingXbox** [comment]
This isn't a specific problem with **zsh** as any good shell script will pick a specific shell for it to run, this script uses **bash** not the specific shell you are using. The script is trying to `source` a script inside the scripts folder. And that's why it will encounter errors.

**Comment by charlie39** [comment]
all the installer scripts(Photoshop, photoshopcusmtom, cameraraw ) sources the sharedfunction.sh script. Literally the first line within the main function in each script sources the shared function script, you can see the line  ( source "sharedFuncs.sh). if you want to run it from the root directory of the repo, then create symlinks to sharedFuncs.sh script in the root directory. But that's really pointless when you can just it by going to the script directory
