### ISSUE TITLE
Crash on big zoom

### ISSUE THREAD

**Issue by xxSkyy** [Gictorbit/photoshopCClinux#37]
I've got crash that logging me out from system when I zoom project to values over 500%

**Comment by xxSkyy** [comment]
Update: This doesnt happen if I'm using integrated graphics instead of nvidia .
After today nvidia update it seems to work to over 1.5k% so no problem so far, I will report if it changes.

**Comment by xxSkyy** [comment]
Nvidia drivers 450 solves atm problem

**Comment by a8underscore** [comment]
Ok please close issue if a graphics driver update fixes issue
