### ISSUE TITLE
Focus lose on additional windows (like liquify)

### ISSUE THREAD

**Issue by xxSkyy** [Gictorbit/photoshopCClinux#38]
Additional windows like liquify losing focus and can't use options and buttons , only workaround for a split second is alt tab there and back.

**Comment by sidneysouza** [comment]
I am too, when i use camera raw, or in export options

**Comment by Gictorbit** [comment]
These kinds of issues come with the Photoshop binary file and as you know it's not open source and I can't solve the problem I'm trying to find a new Photoshop binary more compatible with wine
if I found a way to solve this I will do it
