### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by Notawindowsfan** [Gictorbit/photoshopCClinux#39]
Looks like the drop box links are down, is there a fix?

**Comment by TheDoop** [comment]
I have same problem. download links broken (actually putting files to dropbox not a good idea). Here a logs:
`08/02 17:20:43 [NOTICE] Downloading 1 item(s)

08/02 17:20:43 [NOTICE] CUID#7 - Redirecting to https://www.dropbox.com/s/dl/fmjjrx9xq5a9qqc/vcrun2008.tgz

08/02 17:20:44 [ERROR] CUID#7 - Download aborted. URI=https://www.dropbox.com/s/fmjjrx9xq5a9qqc/vcrun2008.tgz?dl=1
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://www.dropbox.com/s/dl/fmjjrx9xq5a9qqc/vcrun2008.tgz
  -> [HttpSkipResponseCommand.cc:219] errorCode=3 resource not found

08/02 17:20:44 [NOTICE] Download GID#57476e00767f2226 not complete: /home/fdoop/.cache/photoshopCCV19/vcrun2008.tgz

Download results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
57476e|ERR |       0B/s|/home/fdoop/.cache/photoshopCCV19/vcrun2008.tgz

Status Abbreviations:
(ERR):error occurred.

If you restart the transfer, aria2 will continue downloading.
If you encounter an error, check the log file. See the '-l' option on the help and man pages for details.
downloading vcrun2008.tgz ...

08/02 17:20:44 [NOTICE] Downloading 1 item(s)

08/02 17:20:44 [NOTICE] CUID#7 - Redirecting to https://www.dropbox.com/s/dl/fmjjrx9xq5a9qqc/vcrun2008.tgz

08/02 17:20:45 [ERROR] CUID#7 - Download aborted. URI=https://www.dropbox.com/s/fmjjrx9xq5a9qqc/vcrun2008.tgz?dl=1
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://www.dropbox.com/s/dl/fmjjrx9xq5a9qqc/vcrun2008.tgz
  -> [HttpSkipResponseCommand.cc:219] errorCode=3 resource not found

08/02 17:20:45 [NOTICE] Download GID#bd7a24316a7f20d7 not complete: /home/fdoop/.cache/photoshopCCV19/vcrun2008.tgz

Download results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
bd7a24|ERR |       0B/s|/home/fdoop/.cache/photoshopCCV19/vcrun2008.tgz

Status Abbreviations:
(ERR):error occurred.

If you restart the transfer, aria2 will continue downloading.
If you encounter an error, check the log file. See the '-l' option on the help and man pages for details.
error: sorry somthing went wrong during download vcrun2008.tgz
fdoop@laptop:~/İndirilenler/photoshopCClinux$ 
`

**Comment by Gictorbit** [comment]
hi, I checked download URL and it's valid and downloadable.
can you download file directly using `aria2c`? you can check with command below:
`aria2c https://www.dropbox.com/s/dwfyzq2ie6jih7g/photoshopCC-V19.1.6-2018x64.tgz\?dl\=1`

anyway if you need an alternative link here it is
[photoshopCC-V19.1.6-2018x64.tgz](http://dl.gictor.ir/photoshopCC-V19.1.6-2018x64.tgz)

sorry I have not any download server to upload these files so I used free tools. if you have any download server and you can upload our files somewhere it would be great

**Comment by Notawindowsfan** [comment]
Yep I can confirm dropbox is now working no modifications needed, seems like dropbox had a hiccup yesterday. Many thnx for the fast response and keep up the great work Gictorbit!

**Comment by Gictorbit** [comment]
very well thanks
