### ISSUE TITLE
Deepin 15.4.1 launching fail

### ISSUE THREAD

**Issue by LovelinMangang** [Gictorbit/photoshopCClinux#4]
After complete install show this problem:

> ./PhotoshopSetup.sh: line 197: notify-send: command not found
error: sorry something went wrong during install photoshop

**Comment by Gictorbit** [comment]
thank you for reporting this issue
seems Deepin doesn't support `notify-send` 
I made some change can you try again? just run `git pull` in the directory of the repo and run the installation script
