### ISSUE TITLE
Photoshop requires windows 7 or later can't run on this computer

### ISSUE THREAD

**Issue by dkrukshan** [Gictorbit/photoshopCClinux#41]
**Bug**
"Adobe photoshop can't run on this computer. Because this version of photoshop requires windows 7 or later."

**linux Distribution
 - Distro: Ubuntu 20.04
 - Desktop Environment: [Gnome]
 - Installation method:[setup.sh]
 - gpu: [Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)]

**Additional context**
I followed all the steps. But it says "Adobe photoshop can't run on this computer. Because this version of photoshop requires windows 7 or later". In OS selection, windows xp is default for vm. I continued. Error occured on running launcher. Then I installed again & selected windows 7 at the installation, now it worked.

**Comment by Gictorbit** [comment]
just choose windows 7 in `winecfg`
or try method 2 of installation
