### ISSUE TITLE
Choosing Install Directory

### ISSUE THREAD

**Issue by im-ryan** [Gictorbit/photoshopCClinux#42]
I just came upon this repo and was wondering if it's possible to choose where to install Photoshop? I would prefer to not have it in my home directory, and install it on another hard drive with more space.

Also, when you say this is free and does not need a key, do you mean this a pirated copy of Photoshop? Or can we still use our Adobe subscriptions using this method?

**Comment by Gictorbit** [comment]
this is like #9 issue
you can read the solution here [changing installation directory](https://github.com/Gictorbit/photoshopCClinux/issues/22#issuecomment-646446516)

**Comment by im-ryan** [comment]
Thanks for the quick reply, and apologies for not searching about the custom directory.
