### ISSUE TITLE
The dropbox link goes to a 404

### ISSUE THREAD

**Issue by DataAutomator** [Gictorbit/photoshopCClinux#44]
The dropbox link goes to a 404. The installer runs fine until it reaches the downloading portion.

**Comment by donirufatov151220** [comment]
when installing, it gives the error "sorry something went wrong during download vcrun2008.tgz
"

**Comment by oivanrodrigues** [comment]
> The dropbox link goes to a 404. The installer runs fine until it reaches the downloading portion.

**Comment by GalaticStryder** [comment]
Yeah, looks like a problem on dropbox server.

Ideally this should be distributed on a torrent to avoid possible DMCA problems on hosting platforms, not sure if that was the case but sooner or later, if this script becomes more popular, it will certainly be taken down anyway.

And also the modifications to the software (repack) should be more transparent, via scripting, not just some random binary that you can't trust.

**Comment by kam2yar** [comment]
same here

**Comment by Gictorbit** [comment]
hi thank you for reporting this I will fix it as soon as possible
anyway if you need an alternative link here it is
[photoshopCC-V19.1.6-2018x64.tgz](http://dl.gictor.ir/photoshopCC-V19.1.6-2018x64.tgz)

**Comment by Gictorbit** [comment]
hi there I updated broken links
can you please check it again?

**Comment by oivanrodrigues** [comment]
now is perfect, man. Thanks so much!
