### ISSUE TITLE
Crash when running launcher.sh

### ISSUE THREAD

**Issue by djneba** [Gictorbit/photoshopCClinux#45]
**Describe the bug**
When running launcher.sh I get this error from wine:
Unhandled exception: unimplemented function user32.dll.GetDpiForMonitorInternal called in 64-bit code (0x000000007bc6146c)....

**linux Distribution (please complete the following information):**
 - Ubuntu 20.04
 - XFCE
 - Installation method: photoshopSetup.sh (Custom.sh doesn't work)
 - gpu: AMD RX 480
 - display server: X11 (mesa)

**Comment by Gictorbit** [comment]
I made some changes please try again the new version of installer
