### ISSUE TITLE
sorry something went wrong during download wine-3.4.tgz

### ISSUE THREAD

**Issue by czajnik2137** [Gictorbit/photoshopCClinux#49]
**Describe the bug**
I tried to install Photoshop with this script but it keeps failing no matter which script I use (nor default neither custom work). First thing that kinda caught my eye was a line that warned me about missing aria2c even though I installed it through snap minutes ago. The second thing is what causes the script to close - error during wine-3.4 installation. Idk why would it install wine again but it is what it is. Below I include the logs from my console.

[choose an option]$ 2
run photoshop CC Installation...
using custom script for component installation........
scripts/PhotoshopSetupCustom.sh Found...
-d not define default directory used...
-c not define default directory used...
Warning: package aria2c is not installed.
please make sure it's already installed
would you continue? [N/y] y
package wine is installed...
package md5sum is installed...
/home/czajnik/.photoshopCCV19/wine-3.4 directory exists deleting it...
create /home/czajnik/.photoshopCCV19/wine-3.4 directory...
downloading wine-3.4.tgz ...
sharedFuncs.sh: line 276: aria2c: command not found
downloading wine-3.4.tgz ...
sharedFuncs.sh: line 276: aria2c: command not found
error: sorry something went wrong during download wine-3.4.tgz

 - Distro: Debian 10 Buster
 - Desktop Environment: none (only Openbox)
 - Installation method:[e.g.1-photoshopSetup.sh or 2-photoshopSetupCustom.sh ]
 - gpu: 09:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c6)
 - display server: X11

**Comment by Gictorbit** [comment]
please install `aria2` download manager.
installer script uses `aria2` to download components
