### ISSUE TITLE
[Request] Lightroom CC Installer

### ISSUE THREAD

**Issue by WillPower3309** [Gictorbit/photoshopCClinux#54]
Wow, great work getting photoshop working on linux! I'd like to propose adding a lightroom option to the installer, as the two programs are usually used in tandem. I do not have much experience with wine and don't know if this is an unreasonable request, but I'd reckon that photoshop would likely share a lot of wine dependencies with lightroom (in fact even camera raw, which it looks like you've got working, is used in lightroom).

**Comment by Gictorbit** [comment]
thanks, Glad it was useful
ok I will check the lightroom and write an installer for it if it was usable
this thing depends on the wine support and compatibility, even photoshop has some issues
