### ISSUE TITLE
Odd and inconsistent UI scaling

### ISSUE THREAD

**Issue by K4rakara** [Gictorbit/photoshopCClinux#56]
The interface is scaled in a rather hard to describe matter (see picture 1) -- Its as if it's trying to scale for the full screen even though its not being given that. Oddly enough, it sometimes works when the window is in floating mode (see picture 2).

**Install info**
 - Distro: Arch
 - Desktop Environment: None (BSPWM + X11)
 - Installation method: 2-photoshopSetupCustom.sh
 - gpu: AMD Radeon RX570
 - display server: X11

**Screenshots**
![image](https://user-images.githubusercontent.com/40474474/95004523-2c497680-05ba-11eb-9d63-7ebea1a37201.png)
![image](https://user-images.githubusercontent.com/40474474/95004548-85190f00-05ba-11eb-9ea2-92065e3b9e5c.png)

**Comment by hisbaan** [comment]
+1 to this, I have a very similar issue where it won't work properly. The screenshots and floating behaviour is almost identical.

**Info:**
- Distro: Arch
- Kernel: 5.8.11
- WM: bspwm
- Window Server: X11
- GPU: Nvidia GTX1080

If the author never gets around to this, then the semi-solution I found was setting the photoshop window to floating mode in my bspwmrc:

`bspc rule -a Wine:photoshop.exe state=floating`

**Comment by ewen-lbh** [comment]
On i3 scaling is messed up in the same way except the "floating mode" workaround does not work either...

**Comment by ethorne** [comment]
+1 to this as well! Screenshots and description are exactly what I'm seeing on my machine. Would be happy to look into this myself if I someone lmk where to start looking.

- Distro: Ubuntu
- Kernel: 4.15.0
- WM: i3
- Window Server: X11
- GPU: integrated i9

**Comment by PoSayDone** [comment]
Its not a bug, photoshop window is thinking that is fullscreen, and its croped, all you need to fix this just make phtotshop fullscreen in your wm and to press restore button in photoshop window.
![image](https://user-images.githubusercontent.com/29358657/104833208-c9ee5a80-58b8-11eb-8c1d-f01d80cb712c.png)
