### ISSUE TITLE
photoshop.desktop should be copied to ~/.local/share/applications instead of /usr/share/applications

### ISSUE THREAD

**Issue by laurinneff** [Gictorbit/photoshopCClinux#57]
Since Photoshop is installed in the user directory (and not in /opt or somewhere like that) I think it would be better if the .desktop file was copied to the user-specific applications directory instead of the system applications directory.

**Comment by Gictorbit** [comment]
ok that's a good idea I will fix this soon as soon possible thanks

**Comment by ManuLinares** [comment]
Yeah, this. so no **sudo** is needed

**Comment by Gictorbit** [comment]
desktop entry path changed to `.local/...`, but still script needs `sudo` to create `photoshop` command. Otherwise, we should add a new path to `PATH` variable
