### ISSUE TITLE
Using which for checking if package is installed is bad

### ISSUE THREAD

**Issue by FilipLitwora** [Gictorbit/photoshopCClinux#59]
Hello,
I've encountered an issue with your script.

The way you made it check if a package is installed doesn't always work.
For example, I have wine installed and `$ which wine` outputs /bin/wine but your script checks if `$(which wine) == "/usr/bin/wine"`

**Comment by FilipLitwora** [comment]
#60 I made a PR fixing this issue

**Comment by Gictorbit** [comment]
I fixed this issue with your code thanks
