### ISSUE TITLE
installing problem

### ISSUE THREAD

**Issue by mohamedshaban-97** [Gictorbit/photoshopCClinux#6]
having problem in installation phase there is a corrupted link or something 
![Screenshot from 2020-04-04 03-56-58](https://user-images.githubusercontent.com/31129682/78416494-6052d780-7629-11ea-8fc8-e8cb667b2398.png)
![Screenshot from 2020-04-04 03-56-48](https://user-images.githubusercontent.com/31129682/78416496-634dc800-7629-11ea-8914-8136712a0dfc.png)

**Comment by Gictorbit** [comment]
hi I checked the download link and it was correct and downloadable
![image](https://user-images.githubusercontent.com/34630603/78453557-c8e09980-76a7-11ea-8b78-f24299030d78.png)
as you can see the installer script needs several components and fails during download `vcrun2008`
I think it's because of your internet connection can you download this component with below command?
```bash
aria2c "https://www.dropbox.com/s/fmjjrx9xq5a9qqc/vcrun2008.tgz\?dl\=1"
```

**Comment by mohamedshaban-97** [comment]
yeah I can download it easily and my internet connection is good 
![Screenshot from 2020-04-04 19-29-21](https://user-images.githubusercontent.com/31129682/78457489-d21f3580-76aa-11ea-91d2-5c2a642ffde3.png)

**Comment by Gictorbit** [comment]
I tested again and there is no problem

![image](https://user-images.githubusercontent.com/34630603/78649962-797eb100-78d3-11ea-8429-db7247330344.png)

could you please try again and run the installation script?

**Comment by mohamedshaban-97** [comment]
The link in the script doesn't work with me so I changed with the one I this command `aria2c "https://www.dropbox.com/s/fmjjrx9xq5a9qqc/vcrun2008.tgz\?dl\=1"` and it works with me but I got another error 😅
![Screenshot from 2020-04-07 11-38-15](https://user-images.githubusercontent.com/31129682/78654299-9fe92000-78c4-11ea-85df-554a4bc8de98.png)
![Screenshot ](https://user-images.githubusercontent.com/31129682/78654304-a24b7a00-78c4-11ea-96a2-7d4fbfd41974.png)

**Comment by Gictorbit** [comment]
I made some changes can you try again?
first of all update local content of repo with `git pull` and then run `uninstall.sh` script to remove previous photoshop then run `photoshopSetup.sh` it should work

**Comment by mohamedshaban-97** [comment]
![Screenshot from 2020-04-08 18-09-33](https://user-images.githubusercontent.com/31129682/78807593-9810a500-79c4-11ea-921c-d63580ff05f7.png)
![Screenshot from 2020-04-08 18-09-46](https://user-images.githubusercontent.com/31129682/78807601-99da6880-79c4-11ea-8232-82603c1a822a.png)
![Screenshot from 2020-04-08 18-09-52](https://user-images.githubusercontent.com/31129682/78807604-9b0b9580-79c4-11ea-979e-7688deb4e3fc.png)
I got 3 errors with the links again 😥

**Comment by Gictorbit** [comment]
I changed the script to use `winetricks` for components installation,
I tested all links and they are valid I don't know what's your problem.
it's not about installer script as you can see even `winetricks` can't install components maybe aria2c has an issue in your machine
other people tested this and it works
