### ISSUE TITLE
Failed Installing wine gecko

### ISSUE THREAD

**Issue by lauliet501** [Gictorbit/photoshopCClinux#63]
![Screenshot-20201006162907-1920x1080](https://user-images.githubusercontent.com/64822141/95171670-3903df80-07f1-11eb-904b-bf909841d532.png)

**Comment by ramonGonzEdu** [comment]
Thats most likely an issue with your internet connection, I.E. a corrupt file or a MiTM (not likely). Running the installer again should fix it.
