### ISSUE TITLE
Error Download msxml3.msi

### ISSUE THREAD

**Issue by mugi789** [Gictorbit/photoshopCClinux#66]
**Describe the bug**

**linux Distribution (please complete the following information):**
 - Distro: Ubuntu 18.04.4
 - Desktop Environment: Mate
 - Installation method: ./setup.sh
 - gpu: Nvidia
 - display server: [e.g. X11,Wayland]

**Additional context**
[#0ce48a 0B/0B CN:1 DL:0B]                                                                                                
10/17 03:11:42 [ERROR] CUID#7 - Download aborted. URI=ftp://176.9.43.153/MS%20XML%20Parser/msxml3.msi
Exception: [FtpConnection.cc:327] errorCode=1 Got EOF from the server.

10/17 03:11:42 [NOTICE] Download GID#0ce48a78e0bf65c2 not complete: /home/localdisk/.cache/winetricks/msxml3/msxml3.msi

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0ce48a|ERR |       0B/s|/home/localdisk/.cache/winetricks/msxml3/msxml3.msi

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
Executing cd /home/localdisk/.cache/winetricks/msxml3
Downloading https://web.archive.org/web/2000/ftp://176.9.43.153/MS%20XML%20Parser/msxml3.msi to /home/localdisk/.cache/winetricks/msxml3

10/17 03:11:43 [NOTICE] Downloading 1 item(s)
[#7f8055 0B/0B CN:1 DL:0B]                                                                                                
10/17 03:11:50 [ERROR] CUID#7 - Download aborted. URI=https://web.archive.org/web/2000/ftp://176.9.43.153/MS%20XML%20Parser/msxml3.msi
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://web.archive.org/web/2000/ftp://176.9.43.153/MS%20XML%20Parser/msxml3.msi
  -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found

10/17 03:11:50 [NOTICE] Download GID#7f80554b6f2a6f97 not complete: /home/localdisk/.cache/winetricks/msxml3/msxml3.msi

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
7f8055|ERR |       0B/s|/home/localdisk/.cache/winetricks/msxml3/msxml3.msi

Status Legend:
(ERR):error occurred.

**Screenshots**
![Screenshot from 2020-10-17 03-18-09](https://user-images.githubusercontent.com/32443765/96305065-70f7f780-1027-11eb-8f4a-3b5b7b5ef3aa.png)

**Comment by Gictorbit** [comment]
this is because of your internet connection or `winetricks` faults, not installer script
