### ISSUE TITLE
Scale factor too large

### ISSUE THREAD

**Issue by anarchotaoist** [Gictorbit/photoshopCClinux#67]
**Describe the bug**
Upon launching Photoshop I get a pop up.
'Your tool options bar will be clipped because your scale factor is too large. Reduce your monitor settings to a lower scale, or drag Photoshop to a larger monitor'

Photishop UI is cut off. Changing resolution in Kubuntu settings does not change photoshop. 
Laptop set as 1920x1080.
Originally this was not an issue. 

**linux Distribution (please complete the following information):**
 - Distro: Kubuntu  20.04
 - Desktop Environment: kDE Plasma
 - Installation method:[e.g.1-photoshopSetup.sh or 2-photoshopSetupCustom.sh ]
 - gpu: [model of your graphics card on your Laptop powered by Linux e.g. intel,Nvidia,and] you can check with command lspci | grep -i --color 'vga\|3d\|2d'
 - display server: [e.g. X11,Wayland]

**Additional context**

**Screenshots**

**Comment by Gictorbit** [comment]
hi this is photoshop binary fault or wine problem
unfortunately I haven't any solution for this issue
just report installer script bugs
thanks

**Comment by anarchotaoist** [comment]
ok, thanks.

nb. Re-installing gets it working properly again. The issue happens again after a reboot.
