### ISSUE TITLE
error: wine 3.4 config is wrong

### ISSUE THREAD

**Issue by Sabbaot** [Gictorbit/photoshopCClinux#68]
sharedFuncs lie 238: /home/user/.photoshopCCv19/wine-3.4/bin/wine no such file or directory
error: wine 3.4 config is wrong
debian 10
wine-4.0 is installed during
```
sudo apt-get install wine aria2 winetricks
git clone https://github.com/Gictorbit/photoshopCClinux.git
cd photoshopCClinux
chmod +x setup.sh
./setup.sh
2
```
wine 3.4 exists is in /home/user/.photoshopCCV19/wine-3.4

**Comment by xoco70** [comment]
happens here to: Ubuntu 20.04

**Comment by sinyo1015** [comment]
Same here too at Devuan Beowulf

**Comment by Gictorbit** [comment]
we switched to the latest version of wine and this problem solved
