### ISSUE TITLE
Script won't proceed with installation of the Microsoft libraries

### ISSUE THREAD

**Issue by sh1ft-github** [Gictorbit/photoshopCClinux#70]
**Describe the bug**
The script runs fine without errors. The downloading works just fine and the status is (OK):download completed. Once all of the required installation file are downloaded the script continues, detects the photoshopCC-V19.1.6-2018x64.tgz file and extracts it and says "install photoshop ..." and then it gets stuck on "Please don't change default Destionation folder" which to my understanding is the part where the required Windows libraries are supposed to popup and you have to install them. However none of the Windows pop-up.

**linux Distribution (please complete the following information):**
 - Distro: Kali Linux
 - Desktop Environment: [XFCE]
 - Installation method:[1-photoshopSetup.sh]
 - gpu: [AMD RX 5700XT]
 - display server: [X11]

**Additional context**
I have tried restarting the script which didn't fix the issue and I have tried running the script with both root and non-root privileges.

**Comment by RGFTheCoder** [comment]
As soon as a single file is downloaded, the installer appears. The "Please don't change default Destination folder" message appears when the Photoshop installer opens.

**Comment by Gictorbit** [comment]
I made some changes please try again
