### ISSUE TITLE
Why wine 3.4?

### ISSUE THREAD

**Issue by Tachi107** [Gictorbit/photoshopCClinux#71]
I tried starting Photoshop with the wine version I had already installed in my system (wine stable 5.0.2) and everything seems to work just fine. Why does the script download and install an ancient version of wine?

**Comment by charlie39** [comment]
Thanks man, it was crasing in wine 3.4, installed via 5.1, though the installation process was rather patchy but so far I have edited a couple of images and no problem like there was in  3.4. Can also own rawcamera settings which was crashing in 4.3. @Gictorbit I think you need to mention that in README as u have seen some issues mentioning the same problem #32 #34

**Comment by itzvaporwave** [comment]
@charlie39 would you be able to make a script or detail how you did it? thanks.

**Comment by PoorPocketsMcNewHold** [comment]
Or surely better, make a pull request to update the wine version.

**Comment by PoorPocketsMcNewHold** [comment]
Still no answers ? @Gictorbit

**Comment by Gictorbit** [comment]
hello every one, i apologize for the delay in replying. I was busy

> I tried starting Photoshop with the wine version I had already installed in my system (wine stable 5.0.2) and everything seems to work just fine. Why does the script download and install an ancient version of wine?

I tested version 5 of wine before and it has some issues with proprietary nvidia driver, also wine 3.4 was more stable and compatible with photoshop and nvidia so I choosed it

> Thanks man, it was crasing in wine 3.4, installed via 5.1, though the installation process was rather patchy but so far I have edited a couple of images and no problem like there was in 3.4. Can also open rawcamera settings which was crashing in 4.3. @Gictorbit I think you need to mention that in README as u have seen some issues mentioning the same problem #32 #34

interesting, so I will test it and if there was no issues, I will switch to wine 5 in next version

**Comment by Gictorbit** [comment]
Good news we just switched to wine 5

**Comment by Tachi107** [comment]
> Good news we just switched to wine 5

yey
