### ISSUE TITLE
Glimpse Image Editor

### ISSUE THREAD

**Issue by ALipAkrohk** [Gictorbit/photoshopCClinux#73]
You've spent a lot of time developing software on GNU / Linux that may never get into repositories, and there's a good free example of that.
The only significant problem with Gimp right now is the lack of a proper UI, Gimp is much lighter, more efficient and more standard, takes up less Hardware and supports more formats.
Wouldn't it be better to help the Glimpse Image Editor or Gimp user interface design team instead ?!  Why didn't you do that?

**Comment by s7relok** [comment]
Glimpse is just the SJW version of GIMP. Don't use that.
Use and help the original, proven functionning since ages.

And for some thing photoshop is required (use of particular plugins with no opensource equivalent....)
