### ISSUE TITLE
"Brush" Looks like spaced dots

### ISSUE THREAD

**Issue by ArdityoCahyo** [Gictorbit/photoshopCClinux#75]
I found a problem, that when using the brush like spaced dots.
This problem only exists if you use "brush" with a Hardness 0%.

![Screenshot from 2020-12-12 22-05-59](https://user-images.githubusercontent.com/31717689/101987630-f3b7ce80-3cc7-11eb-8ed2-d6d57c31f1a0.png)

I put a red dot for clarity. Here,

![Screenshot from 2020-12-12 22-06-42](https://user-images.githubusercontent.com/31717689/101987666-311c5c00-3cc8-11eb-925e-7b6ce1d3d8f8.png)

**Comment by Gictorbit** [comment]
hi this is photoshop binary fault and I haven't any solution for this issue
just report installer script bugs
