### ISSUE TITLE
Can't open TIFF files

### ISSUE THREAD

**Issue by RGFTheCoder** [Gictorbit/photoshopCClinux#76]
**Describe the bug**
I am able to create a new file and save it as a tiff, but I can't load it afterwards.

**linux Distribution (please complete the following information):**
 - Distro: Kubuntu 20.10
 - Desktop Environment: KDE
 - Installation method: photoshopSetupCustom.sh ]
 - gpu: NVIDIA Corporation GP106 [GeForce GTX 1060 3GB] (rev a1)
 - display server: KWin
 
![Screenshot_20201216_110903-1](https://user-images.githubusercontent.com/24970643/102374326-33fca280-3f8f-11eb-969f-c7cca8440e87.png)

[backtrace.txt](https://github.com/Gictorbit/photoshopCClinux/files/5703943/backtrace.txt)

**Comment by Gictorbit** [comment]
I tested a `TIF` file right now, and it works
maybe your file is damaged?

**Comment by RGFTheCoder** [comment]
I don't currently have access to the machine on which the error is apparent. I will try another file when possible (2-3 days?). Could you provide a TIFF file you verified to be working? The TIFF file I'm attempting to open in PS shows properly in gwenview and I can "Save As..." as a PNG file. Attempting to open TIFF and NEF files crashes it, so I'm having to convert my NEF files to png's in gwenview and then open those in PS and save as a PSD, but I don't want to lose the TIF files I've made and CloudConvert flattens the TIFF file.

**Comment by Gictorbit** [comment]
I tested these files provided on `fileformat` website and tried to open samples in PS, and it worked fine
[https://www.fileformat.info/format/tiff/sample/index.htm](https://www.fileformat.info/format/tiff/sample/index.htm)
