### ISSUE TITLE
Endless Almost Finish?

### ISSUE THREAD

**Issue by EgorFlame** [Gictorbit/photoshopCClinux#77]
**Describe the bug**
Endless "Almost Finish" process.

**linux Distribution (please complete the following information):**
 - Distro: [ArcoLinux]
 - Desktop Environment: [KDE]
 - Installation method: [both]
 - gpu: [AMD Radeon HD 8870M]
 - display server: [X11]

Everything runs perfectly, and then I get endless "Almost Finish" in my terminal. The service is active, not a zombie, and it actually eats slightly different ammount of RAM every second, but I can't run any other command in terminal, and it literally never ends (I waited more than hour). I just don't know is my installation finished or not, ergo, can not use Photoshop properly.

**Comment by Gictorbit** [comment]
The "almost finish" is a message that will be print at the end of installation, so if you see this message it means the program installed correctly
