### ISSUE TITLE
aria2c not installed 

### ISSUE THREAD

**Issue by ZenoX9999** [Gictorbit/photoshopCClinux#78]
### the script tells me aria2c is not installed even tho it is (through apt), after selecting yes it it installed the script crashes.
this is the whole output:

`[choose an option]$ 1
run photoshop CC Installation...
using winetricks for component installation........
scripts/PhotoshopSetup.sh Found...
-d not define default directory used...
-c not define default directory used...
Warning: package aria2c is not installed.
please make sure it's already installed
would you continue? [N/y] y
package wine is installed...
package md5sum is installed...
package winetricks is installed...
/home/martin/.photoshopCCV19/wine-3.4 directory exists deleting it...
create /home/martin/.photoshopCCV19/wine-3.4 directory...
wine-3.4.tgz detected
wine 3.4 installed...
/home/martin/.photoshopCCV19/prefix directory exists deleting it...
create /home/martin/.photoshopCCV19/prefix directory...
wine variables exported...
wine 3.4 is configured...
please install mono and gecko packages then click on ok button
prefix configured...
add necessary DLLs...
set dark mode for wine...
/home/martin/.photoshopCCV19/resources directory exists deleting it...
create /home/martin/.photoshopCCV19/resources directory...
------------------------------------------------------
Your version of wine 3.4 is no longer supported upstream. You should upgrade to 4.x
------------------------------------------------------
Executing mkdir -p /home/martin/.photoshopCCV19
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412 - sha256sum: 7651c93e39fcb080483c38836513bf912273a87ea97d137f6b958ed3d9628c3d with wine-3.4 and WINEARCH=win64
Executing w_do_call atmlib
Executing mkdir -p /home/martin/.photoshopCCV19
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_atmlib 
Executing cd /home/martin/.cache/winetricks/win2ksp4
Downloading https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE to /home/martin/.cache/winetricks/win2ksp4
12/18 18:37:30 [NOTICE] Downloading 1 item(s)
12/18 18:37:30 [ERROR] CUID#7 - Download aborted. URI=https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
  -> [InitiateConnectionCommandFactory.cc:87] errorCode=1 https is not supported yet.
12/18 18:37:30 [NOTICE] Download GID#a129b293aba99fc9 not complete: /home/martin/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
a129b2|ERR |        n/a|/home/martin/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE
Status Legend:
(ERR):error occurred.
aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
cat: /tmp/winetricks.mw65cewT/stdout.tmp: No such file or directory
rm: cannot remove '/tmp/winetricks.mw65cewT/stdout.tmp': No such file or directory
cat: /tmp/winetricks.mw65cewT/stdout.tmp: No such file or directory
rm: cannot remove '/tmp/winetricks.mw65cewT/stdout.tmp': No such file or directory
Executing cd /home/martin/.cache/winetricks/win2ksp4
Downloading https://web.archive.org/web/2000/https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE to /home/martin/.cache/winetricks/win2ksp4
12/18 18:37:30 [NOTICE] Downloading 1 item(s)
12/18 18:37:30 [ERROR] CUID#7 - Download aborted. URI=https://web.archive.org/web/2000/https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://web.archive.org/web/2000/https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
  -> [InitiateConnectionCommandFactory.cc:87] errorCode=1 https is not supported yet.
12/18 18:37:30 [NOTICE] Download GID#b16c27bcaf05b168 not complete: /home/martin/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
b16c27|ERR |        n/a|/home/martin/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE
Status Legend:
(ERR):error occurred.
aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
------------------------------------------------------
Downloading https://web.archive.org/web/2000/https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE failed
------------------------------------------------------
downloading photoshopCC-V19.1.6-2018x64.tgz ...
12/18 18:37:33 [NOTICE] Downloading 1 item(s)
12/18 18:37:33 [ERROR] CUID#7 - Download aborted. URI=https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz
  -> [InitiateConnectionCommandFactory.cc:87] errorCode=1 https is not supported yet.
12/18 18:37:33 [NOTICE] Download GID#371588abc50895fc not complete: /home/martin/.cache/photoshopCCV19/photoshopCC-V19.1.6-2018x64.tgz
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
371588|ERR |        n/a|/home/martin/.cache/photoshopCCV19/photoshopCC-V19.1.6-2018x64.tgz
Status Legend:
(ERR):error occurred.
aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
downloading photoshopCC-V19.1.6-2018x64.tgz ...
12/18 18:37:33 [NOTICE] Downloading 1 item(s)
12/18 18:37:33 [ERROR] CUID#7 - Download aborted. URI=https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz
  -> [InitiateConnectionCommandFactory.cc:87] errorCode=1 https is not supported yet.
12/18 18:37:33 [NOTICE] Download GID#9b7704037416b47d not complete: /home/martin/.cache/photoshopCCV19/photoshopCC-V19.1.6-2018x64.tgz
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
9b7704|ERR |        n/a|/home/martin/.cache/photoshopCCV19/photoshopCC-V19.1.6-2018x64.tgz
Status Legend:
(ERR):error occurred.
aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
error: sorry something went wrong during download photoshopCC-V19.1.6-2018x64.tgz
`

### my linux:
Ubuntu 20.04.1 LTS
gnome : 3.36.3

this is really weird because when i run aria2c in terminal it clearly works what could be the problem?

**Comment by Gictorbit** [comment]
What is the output of command `aria2c` ?
if you have installed it correctly it returns some output for example command `aria2c -v` shows version of aria download manager

**Comment by ZenoX9999** [comment]
```
martin@martin-Blade:~$ aria2c -v
aria2 version 1.35.0
Copyright (C) 2006, 2019 Tatsuhiro Tsujikawa

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

** Configuration **
Enabled Features: BitTorrent, GZip, Message Digest, Metalink, XML-RPC
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.11 expat/2.2.9
Compiler: gcc 9.3.0
  built by  x86_64-pc-linux-gnu
  on        Nov 23 2020 11:24:13
System: Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64

Report bugs to https://github.com/aria2/aria2/issues
Visit https://aria2.github.io/
```

**Comment by Gictorbit** [comment]
hi please try new version of installer I made some changes
