### ISSUE TITLE
Downloads not working with aria2c, but work with wget

### ISSUE THREAD

**Issue by firepol** [Gictorbit/photoshopCClinux#79]
**Describe the bug**
Setup starts but does has download errors. It seems it doesn't download anything because of those errors. If I copy/paste the URLs it tries to download in the browser (e.g. Chromium), the browser can download them. Some URLs are broken, but I see the setup tries a few variants, but never succeeds. If one url is 404 and I try a working one, I can download the files via browser.

I tried some urls via aria2c and they don't work. With wget they work. An easy fix is to change aria2c with wget.

Note, in ubuntu aria3c is not provided in the standard packages, it must be installed via snap:
`snap install aria2c`

For better compatibility I suggest to simply use wget. wget is quite a standard package that can be found anywhere. In fact before today I never heard of aria2c...

**linux Distribution (please complete the following information):**
 - Distro: Ubuntu 20.04 LTS
 - Desktop Environment: Gnome
 - gpu: NVIDIA Corporation GM204 [GeForce GTX 980] (rev a1)
 - display server: xorg

aria2c version:

`aria2c --version`
aria2 version 1.35.0
Copyright (C) 2006, 2019 Tatsuhiro Tsujikawa

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.11 libxml2/2.9.10 sqlite3/3.22.0 OpenSSL/1.1.1g c-ares/1.14.0 libssh2/1.8.0
Compiler: gcc 7.5.0
  built by  x86_64-pc-linux-gnu
  on        Jul  5 2020 03:08:11
System: Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64

Report bugs to https://github.com/aria2/aria2/issues
Visit https://aria2.github.io/

**Additional context**
wget https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
not working

wget https://web.archive.org/web/2000/https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
works

aria2c https://web.archive.org/web/2000/https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
does not work, see error:

01/04 13:27:33 [NOTICE] Downloading 1 item(s)

01/04 13:27:34 [NOTICE] CUID#7 - Redirecting to https://web.archive.org/web/20180613014937/https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE

01/04 13:27:34 [NOTICE] CUID#7 - Redirecting to https://web.archive.org/web/20180613014937/https://saimei.ftp.acc.umu.se/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
[#6ce764 0B/0B CN:1 DL:0B]                                                                                                                 
01/04 13:27:35 [NOTICE] CUID#7 - Redirecting to https://web.archive.org/web/20180613014941/https://saimei.ftp.acc.umu.se/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE

01/04 13:27:35 [ERROR] CUID#7 - Download aborted. URI=https://web.archive.org/web/2000/https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
Exception: [AbstractCommand.cc:351] errorCode=16 URI=https://web.archive.org/web/20180613014941/https://saimei.ftp.acc.umu.se/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
  -> [AbstractDiskWriter.cc:224] errNum=13 errorCode=16 Failed to open the file /var/lib/snapd/void/W2KSP4_EN.EXE, cause: Permission denied

01/04 13:27:35 [NOTICE] Download GID#6ce7648285296dcb not complete: /var/lib/snapd/void/W2KSP4_EN.EXE

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
6ce764|ERR |       0B/s|/var/lib/snapd/void/W2KSP4_EN.EXE

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

**Screenshots**

[choose an option]$ 1
run photoshop CC Installation...
using winetricks for component installation........
scripts/PhotoshopSetup.sh Found...
-d not define default directory used...
-c not define default directory used...
is64 checked...
package aria2c is installed...
package wine is installed...
package md5sum is installed...
package winetricks is installed...
/home/firepol/.photoshopCCV19/prefix directory exists deleting it...
create /home/firepol/.photoshopCCV19/prefix directory...
wine variables exported...
please install mono and gecko packages then click on OK button
prefix configured...
set dark mode for wine...
/home/firepol/.photoshopCCV19/resources directory exists deleting it...
create /home/firepol/.photoshopCCV19/resources directory...
Executing mkdir -p /home/firepol/.photoshopCCV19
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412 - sha256sum: 7651c93e39fcb080483c38836513bf912273a87ea97d137f6b958ed3d9628c3d with wine-5.0 (Ubuntu 5.0-3ubuntu1) and WINEARCH=win64
Executing w_do_call atmlib
Executing mkdir -p /home/firepol/.photoshopCCV19
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_atmlib 
Executing cd /home/firepol/.cache/winetricks/win2ksp4
Downloading https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE to /home/firepol/.cache/winetricks/win2ksp4

01/04 13:18:14 [NOTICE] Downloading 1 item(s)

01/04 13:18:15 [ERROR] CUID#7 - Download aborted. URI=https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
  -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found

01/04 13:18:15 [NOTICE] Download GID#1f23901a3a60a2dc not complete: /home/firepol/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
1f2390|ERR |       0B/s|/home/firepol/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
cat: /tmp/winetricks.MnGIPPdz/stdout.tmp: No such file or directory
rm: cannot remove '/tmp/winetricks.MnGIPPdz/stdout.tmp': No such file or directory
cat: /tmp/winetricks.MnGIPPdz/stdout.tmp: No such file or directory
rm: cannot remove '/tmp/winetricks.MnGIPPdz/stdout.tmp': No such file or directory
Executing cd /home/firepol/.cache/winetricks/win2ksp4
Downloading https://web.archive.org/web/2000/https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE to /home/firepol/.cache/winetricks/win2ksp4

01/04 13:18:16 [NOTICE] Downloading 1 item(s)
[#a2f6cd 0B/0B CN:1 DL:0B]                                                                                                                 
01/04 13:18:17 [NOTICE] CUID#7 - Redirecting to https://web.archive.org/web/20180613014937/https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE

01/04 13:18:17 [NOTICE] CUID#7 - Redirecting to https://web.archive.org/web/20180613014937/https://saimei.ftp.acc.umu.se/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
[#a2f6cd 0B/0B CN:1 DL:0B]                                                                                                                 
01/04 13:18:18 [NOTICE] CUID#7 - Redirecting to https://web.archive.org/web/20180613014941/https://saimei.ftp.acc.umu.se/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
[#a2f6cd 0B/0B CN:1 DL:0B]                                                                                                                 
01/04 13:18:22 [ERROR] CUID#7 - Download aborted. URI=https://web.archive.org/web/2000/https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
Exception: [AbstractCommand.cc:351] errorCode=16 URI=https://web.archive.org/web/20180613014941/https://saimei.ftp.acc.umu.se/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
  -> [AbstractDiskWriter.cc:224] errNum=13 errorCode=16 Failed to open the file /home/firepol/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE, cause: Permission denied

01/04 13:18:22 [NOTICE] Download GID#a2f6cd24d33aa136 not complete: /home/firepol/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
a2f6cd|ERR |       0B/s|/home/firepol/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
------------------------------------------------------
Downloading https://web.archive.org/web/2000/https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE failed
------------------------------------------------------
downloading photoshopCC-V19.1.6-2018x64.tgz ...

01/04 13:18:25 [NOTICE] Downloading 1 item(s)

01/04 13:18:26 [ERROR] CUID#7 - Download aborted. URI=https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz
Exception: [AbstractCommand.cc:403] errorCode=16 URI=https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz
  -> [RequestGroup.cc:760] errorCode=16 Download aborted.
  -> [AbstractDiskWriter.cc:224] errNum=13 errorCode=16 Failed to open the file /home/firepol/.cache/photoshopCCV19/photoshopCC-V19.1.6-2018x64.tgz, cause: Permission denied

01/04 13:18:26 [NOTICE] Download GID#9ad8c8c9688e564a not complete: /home/firepol/.cache/photoshopCCV19/photoshopCC-V19.1.6-2018x64.tgz

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
9ad8c8|ERR |       0B/s|/home/firepol/.cache/photoshopCCV19/photoshopCC-V19.1.6-2018x64.tgz

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
downloading photoshopCC-V19.1.6-2018x64.tgz ...

01/04 13:18:26 [NOTICE] Downloading 1 item(s)

01/04 13:18:26 [ERROR] CUID#7 - Download aborted. URI=https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz
Exception: [AbstractCommand.cc:403] errorCode=16 URI=https://victor.poshtiban.io/p/gictor/photoshopCC/photoshopCC-V19.1.6-2018x64.tgz
  -> [RequestGroup.cc:760] errorCode=16 Download aborted.
  -> [AbstractDiskWriter.cc:224] errNum=13 errorCode=16 Failed to open the file /home/firepol/.cache/photoshopCCV19/photoshopCC-V19.1.6-2018x64.tgz, cause: Permission denied

01/04 13:18:26 [NOTICE] Download GID#ca5880914ae3078f not complete: /home/firepol/.cache/photoshopCCV19/photoshopCC-V19.1.6-2018x64.tgz

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
ca5880|ERR |       0B/s|/home/firepol/.cache/photoshopCCV19/photoshopCC-V19.1.6-2018x64.tgz

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
error: sorry something went wrong during download photoshopCC-V19.1.6-2018x64.tgz

**Comment by firepol** [comment]
**Solution**

I tried with wget, but somehow replacing the aria2c command with the wget version, I mean

Replacing

aria2c -c -x 8 -d $CACHE_PATH -o $4 $3

with:

wget $3 -P $CACHE_PATH

Seems to do the job. Just like this I see that the md5 checksum at the end of the download isn't done. But I could get my installation working in case somebody wants a quick solution.

**Comment by Gictorbit** [comment]
Thank you for your report.
I changed the installer script to use `wget` instead of `Aria2c` to download files

**Comment by HarikrishnanMarathayil** [comment]
┏━━━━━━━━━━━━━━━━━━━━━━━━━┫ Photoshop CC Installer ┣━━━━━━━━━━━━━━━━━━━━━━━━┓
                     ┃                                                                           ┃
  ███████████████████████████                                                                    ┃
  ██                       ██      1- Install photoshop CC                                       ┃
  ██  ███████▆▃            ██                                                                    ┃
  ██  ███   ▝██▙           ██      2- Install adobe camera raw v12                               ┃
  ██  ███    ███           ██                                                                    ┃
  ██  ███   ▟██▛▗▟████▙    ██      3- configure virtual drive          (winecfg)                 ┃
  ██  ███████▛  ██▋        ██                                                                    ┃
  ██  ███       ▝▜█████▙   ██      4- uninstall photoshop                                        ┃
  ██  ███             ██▌  ██                                                                    ┃
  ██  ███        ▗▟████▛   ██      5- exit                                                       ┃
  ██                       ██                                                                    ┃
  ███████████████████████████                                                                    ┃
                     ┃                                                                           ┃
                     ┗━━━━━━━━━━━━━━━┫ https://github.com/Gictorbit/photoshopCClinux ┣━━━━━━━━━━━┛

[choose an option]$ 1
run photoshop CC Installation...
using winetricks for component installation........
scripts/PhotoshopSetup.sh Found...
-d not define default directory used...
-c not define default directory used...
is64 checked...
package wine is installed...
package wine64 is installed...
package md5sum is installed...
package winetricks is installed...
/home/ubuntu/.photoshopCCV19/prefix directory exists deleting it...
create /home/ubuntu/.photoshopCCV19/prefix directory...
wine variables exported...
please install mono and gecko packages then click on OK button, do not change Windows version from Windows 7
prefix configured...
set dark mode for wine...
/home/ubuntu/.photoshopCCV19/resources directory exists deleting it...
create /home/ubuntu/.photoshopCCV19/resources directory...
Executing mkdir -p /home/ubuntu/.photoshopCCV19
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412 - sha256sum: 7651c93e39fcb080483c38836513bf912273a87ea97d137f6b958ed3d9628c3d with wine-5.0 (Ubuntu 5.0-3ubuntu1) and WINEARCH=win64
Executing w_do_call atmlib
Executing mkdir -p /home/ubuntu/.photoshopCCV19
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_atmlib 
Executing cabextract -q -d /home/ubuntu/.photoshopCCV19/prefix/dosdevices/c:/windows/temp -L -F i386/atmlib.dl_ /home/ubuntu/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE
Executing cabextract -q --directory=/home/ubuntu/.photoshopCCV19/prefix/dosdevices/c:/windows/syswow64 /home/ubuntu/.photoshopCCV19/prefix/dosdevices/c:/windows/temp/i386/atmlib.dl_
Executing w_do_call fontsmooth=rgb
Executing mkdir -p /home/ubuntu/.photoshopCCV19
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_fontsmooth rgb
Setting font smoothing to rgb
Executing wine regedit C:\windows\Temp\fontsmooth.reg
Executing wine64 regedit C:\windows\Temp\fontsmooth.reg
Executing w_do_call vcrun2008
Executing mkdir -p /home/ubuntu/.photoshopCCV19
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_vcrun2008 
------------------------------------------------------
Checksum for /home/ubuntu/.cache/winetricks/vcrun2008/vcredist_x86.exe did not match, retrying download
------------------------------------------------------
Executing cd /home/ubuntu/.cache/winetricks/vcrun2008
Downloading https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe to /home/ubuntu/.cache/winetricks/vcrun2008
--2022-02-16 18:14:35--  https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe
Resolving download.microsoft.com (download.microsoft.com)... 173.222.77.193, 2600:140f:2400:1b0::e59, 2600:140f:2400:18c::e59
Connecting to download.microsoft.com (download.microsoft.com)|173.222.77.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4483040 (4.3M) [application/octet-stream]
Saving to: ‘vcredist_x86.exe’

vcredist_x86.exe                    100%[===================================================================>]   4.27M  9.08MB/s    in 0.5s    

2022-02-16 18:14:36 (9.08 MB/s) - ‘vcredist_x86.exe’ saved [4483040/4483040]

Executing cd /home/ubuntu/photoshopCClinux/scripts
------------------------------------------------------
sha256sum mismatch! Rename /home/ubuntu/.cache/winetricks/vcrun2008/vcredist_x86.exe and try again.
------------------------------------------------------
downloading photoshopCC-V19.1.6-2018x64.tgz ...
using curl to download photoshopCC-V19.1.6-2018x64.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
downloading photoshopCC-V19.1.6-2018x64.tgz ...
using curl to download photoshopCC-V19.1.6-2018x64.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
downloading photoshopCC-V19.1.6-2018x64.tgz ...
using curl to download photoshopCC-V19.1.6-2018x64.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
error: sorry something went wrong during download photoshopCC-V19.1.6-2018x64.tgz
ubuntu@ubuntu-Lenovo-ideapad-310-15ISK:~/photoshopCClinux$ 
 
This is what's happening. I am new to linux and completely lost... Can someone please tell me step by step instruction to fix this?
