### ISSUE TITLE
File | Edit | Image | Layer bar missing on i3

### ISSUE THREAD

**Issue by prankousky** [Gictorbit/photoshopCClinux#80]
Hi,

thank you so much for this script! It is fantastic to have Photoshop CC run on Linux.

However, unfortunately, I am missing the top bar that contains File Edit Image Layer etc. etc.; my WM is `i3-gaps`. It does not make a difference whether I run this in full screen or as a floating window. The top bar is always missing.

There is one workaround: switch from fullscreen to float, then back to fullscreen. This will give me the bar **once**, so I can use the menu as long as the mouse hovers above it. Once I click (either an option, or just anywhere in Photoshop), the top bar disappears again. The only way to get it back is to do this switching cycle again.

Is there something I need to change, or is this a known bug and cannot be fixed? The preview image on the repo's main page looks like the bar should be there, but it isn't.

I run `Arch Linux` with `Xorg` and `i3-gaps`. `picom` is installed, but currently not enabled. `wine` and `winetricks` are installed. I used the install script from this repo, and other than  the top bar missing, everything works fine. 

Thank you in advance for your support :)

**Comment by prankousky** [comment]
Small update: the issue here seems to be connected to `polybar`. When I `pkill polybar`, the bar becomes visible. This seems to be the only way to get around this. Unfortunately, I need polybar. I asked in the polybar subreddit, but will keep this issue here open. If I find a solution, I will post it here.

**Comment by Gictorbit** [comment]
Hi, thank you for great explanation
I do not have much experience in `i3` window manager and I use `gnome` most of the time and I think this is more about `i3` and `wine` so if I found a solution for this issue I will post it

**Comment by Gictorbit** [comment]
Also, I think this it related to #56 issue

**Comment by prankousky** [comment]
Thank you! @Gictorbit 

The solution provided in the linked issue works perfectly.
