### ISSUE TITLE
Glitches in photoshop window

### ISSUE THREAD

**Issue by PoSayDone** [Gictorbit/photoshopCClinux#82]
Distro: Arch
    Desktop Environment: None (BSPWM + X11)
    Installation method: through setup.sh
    gpu: AMD Radeon RX5700XT
    display server: X11
![screenshot_20210117_121439](https://user-images.githubusercontent.com/29358657/104833914-f8226900-58bd-11eb-8363-fc51a16e6b83.png)
![image](https://user-images.githubusercontent.com/29358657/104833942-2f911580-58be-11eb-9406-11c32847dea1.png)
![image](https://user-images.githubusercontent.com/29358657/104834053-c8c02c00-58be-11eb-92a8-5c41c2f6d035.png)

**Comment by Gictorbit** [comment]
That's weird, I didn't have any problem like that on gnome before, but I think this because of photoshop binary file or wine or your DE, and it's not installer script issue, so I don't know what the problem is and unfortunately I have not any solution for it in this time  but if I found solution I will post it here

**Comment by PoSayDone** [comment]
> That's weird, I didn't have any problem like that on gnome before, but I think this because of photoshop binary file or wine or your DE, and it's not installer script issue, so I don't know what the problem is and unfortunately I have not any solution for it in this time but if I found solution I will post it here

Interesting thing, I reinstalled my distro 2 days ago, and I had some small glithes before, but now they are really annoying, maybe I had an old version of this photoshop which was working on wine 3?

**Comment by Gictorbit** [comment]
Yes we optimized the installer to use wine5 instead of 3.4, and some issues solved I highly recommend you to update the installer and reinstall photoshop, so it uses the default version of wine installed on your system I hope it solves the problem

**Comment by PoSayDone** [comment]
I had wine-staging installed, after installing normal wine glitches are disappeared
