### ISSUE TITLE
Stuck on "install photoshop..."

### ISSUE THREAD

**Issue by Random-Pickle** [Gictorbit/photoshopCClinux#84]
I'm trying to install it by running setup.sh, everything worked fine and all dependencies installed successfully but
it gets stuck here
```
photoshopCC-V19.1.6-2018x64.tgz detected
extract photoshop...
install photoshop...
Please don't change default Destination Folder
```

I got stuck there for more than an hour, I tried 2-3 times but the same thing happens.
It doesn't open any Installation Window it just runs a Task that runs for eternity 
![](https://i.imgur.com/N7f0Eld.png)

linux Distribution:
 - Distro: Manjaro 5.9.16
 - Desktop Environment: XFCE
 - gpu: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
 - display server: X11
 
Why the installation window isn't opening?
 
 Thanks for Helping :)

**Comment by Gictorbit** [comment]
hi can you send me log file?

**Comment by Random-Pickle** [comment]
Which one?
I also forgot to mention I'm getting this warning
```
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
```
Is this creating the Issue?

**Comment by Random-Pickle** [comment]
[wine-error.log](https://pastebin.com/raw/8bfpvPxH)
[setuplog.log](https://pastebin.com/raw/4sBx8sD0)

**Comment by Random-Pickle** [comment]
The Installation windows launches when I run it out of the script
![](https://i.imgur.com/6bd2bAw.png)

**Comment by Gictorbit** [comment]
I checked your log files and found that you have already installed Photoshop several times. It is true? Was it working correctly before?
Did you change the destination folder?
I highly recommend you using uninstall option before reinstalling

**Comment by Random-Pickle** [comment]
I've tried few times...So I'll delete the old installations
And I didn't changed destination folder.
Thanks

**Comment by Random-Pickle** [comment]
> Which one?
> I also forgot to mention I'm getting this warning
> 
> ```
> ------------------------------------------------------
> warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> ------------------------------------------------------
> ```
> 
> Is this creating the Issue?

This isn't any issue?

**Comment by Gictorbit** [comment]
It is just a warning and I think it's not related to this issue
I tested the script too many times and I have never seen any problem like that before it's strange
could you please uninstall everything with uninstall option provided in `setup.sh` and try to install it again?

**Comment by Random-Pickle** [comment]
Yes I'm doing that only but why it's downloading photoshopCC-V19.1.6-2018x64.tgz again?
it's already present in /home/random-pickle/.cache/photoshopCCV19
Is there a way to avoid the download? I have photoshopCC-V19.1.6-2018x64.tgz on my pc already.

**Comment by Gictorbit** [comment]
You can use `-c` flag to specify cache directory, which is explained in README
and if this file exists in your cache directory, installer script would avoid redownloading that

**Comment by Random-Pickle** [comment]
Thanks, It detected the file but the same thing is happening again I guess.
[wine-error.log](https://pastebin.com/raw/fUVNDePD)

**Comment by Random-Pickle** [comment]
> 00ac:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
> 00ac:err:winediag:nodrv_CreateWindow The explorer process failed to start.
Something wrong with Driver Installations?

**Comment by Gictorbit** [comment]
Yes Maybe it's because of your wine configuration or something. What is your wine version?

**Comment by Random-Pickle** [comment]
wine-6.0

**Comment by Random-Pickle** [comment]
```
===============| photoshop CC v19 |===============
0054:err:ntdll:RtlpWaitForCriticalSection section 000000007BC63540 "../wine/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0054, blocked by 005c, retrying (60 sec)
003c:err:service:process_send_command receiving command result timed out
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"NDIS" failed to start: 1053
wine: Unhandled page fault on read access to 0000000000000040 at address 00000000004036CB (thread 003c), starting debugger...
MESA-INTEL: warning: Haswell Vulkan support is incomplete
0090:err:clipboard:convert_selection Timed out waiting for SelectionNotify event
0024:err:environ:run_wineboot boot event wait timed out
0080:err:ole:start_rpcss Failed to open service manager
00a0:fixme:console:default_ctrl_handler Terminating process 20 on event 0
008c:err:ole:start_rpcss Failed to open service manager
008c:err:ole:start_rpcss Failed to open service manager
```

New Error Log

**Comment by Gictorbit** [comment]
I'm currently using version 6 too, and everything works fine, that is weird
anyway If I found any solution for this issue I will post it here

I think the newer version of wine is improved enough, and I think the Photoshop setup binary will work well even without these components and dependencies, so you can install ‍‍‍‍`photoshopCC-V19.1.6-2018x64.tgz` you've already downloaded and  just install it using wine without installer script if it worked fine and everything was ok it's our installer script fault definitely

**Comment by Random-Pickle** [comment]
I deleted .wine folder and ran the script again freshly now Installer Window Appeared.
Let's see if it install or my faith have more Errors for me.

**Comment by Random-Pickle** [comment]
It finally woked, I successfully installed it.
Possible Problem I had was Messed up Wine Configuration.
After deleting `.wine` file and uninstalling photoshop by `setup.sh`
And reinstalling worked. No errors at all.
Thanks for your time.

**Comment by Gictorbit** [comment]
very well, good luck
