### ISSUE TITLE
error: sorry something went wrong during photoshop installation

### ISSUE THREAD

**Issue by yakupsevik** [Gictorbit/photoshopCClinux#85]
![2021-01-30_00-16](https://user-images.githubusercontent.com/55827920/106328177-68eb5d00-6290-11eb-9c7d-982739a96a6a.png)

error: sorry something went wrong during photoshop installation

Please help me. :c

**Comment by Gictorbit** [comment]
Did you change default destination folder?

**Comment by yakupsevik** [comment]
I don't know. How can i check?

> Did you change default destination folder?

**Comment by Gictorbit** [comment]
you should choose the default path when setup window appears
dd you change destination folder?
![image](https://user-images.githubusercontent.com/34630603/106349341-80533600-62e2-11eb-963e-396b8871b843.png)

**Comment by yakupsevik** [comment]
I found the problem. Wine32 not properly installed. I solved the problem. Thank you so much Victor!
