### ISSUE TITLE
Crashind, after starting dials

### ISSUE THREAD

**Issue by Destyrr** [Gictorbit/photoshopCClinux#89]
**After photoshop, start dials, wine reports an error, how do I fix it? I really need to use photoshop!**

### **Error:**

![Screenshot from 2021-03-03 11-35-18](https://user-images.githubusercontent.com/79557507/109821777-1695b700-7c15-11eb-93aa-33a0af9eff21.png)

**Comment by Gictorbit** [comment]
What version of `wine` do you have? you can check it with command below:
```
wine --version
```

**Comment by Narendra471411** [comment]
i have also same problem. how to solve this ?

**Comment by Narendra471411** [comment]
> installed

![error](https://user-images.githubusercontent.com/80357130/110530826-e2545600-8140-11eb-9c41-7949f31fb56e.png)

**Comment by Fallstop** [comment]
Had this problem in Wine 5.0 (Kubuntu), uninstalled photoshop and then updated my wine to v6.0. This worked and now it starts as expected. Try this if you also have the problem, as Ubuntu distributes wine v5 under the wine apt package.

**Comment by Narendra471411** [comment]
> Had this problem in Wine 5.0 (Kubuntu), uninstalled photoshop and then updated my wine to v6.0. This worked and now it starts as expected. Try this if you also have the problem, as Ubuntu distributes wine v5 under the wine apt package.

i followed these instructions but again appear same problem
![again](https://user-images.githubusercontent.com/80357130/110931285-16519600-8350-11eb-827c-bdb6b3d9a068.png)

**Comment by Fallstop** [comment]
Reinstalled it a few times, and totally works consistently on my machine, good luck with solving your problem.
