### ISSUE TITLE
Changing installation folder

### ISSUE THREAD

**Issue by NdranC** [Gictorbit/photoshopCClinux#9]
It would be great if you could format the scripts to allow easy change of the installation folder. Doesn't seem overly hard, from what I can tell I would have to change the default path in every single script file and the .desktop file.

I also noticed you misspelled launcher.sh as luncher.sh. Not a big deal but I figured I should point it out.

Last thing. Where did you get this version of photoshop? Is hosted in dropbox but who made it? Is there anything special about it besides begin cracked and having a custom splash screen?

**Comment by Gictorbit** [comment]
> It would be great if you could format the scripts to allow easy change of the installation folder. Doesn't seem overly hard, from what I can tell I would have to change the default path in every single script file and the .desktop file.

ok thanks for your suggestion
I will add some argument for optional paths

> I also noticed you misspelled launcher.sh as luncher.sh. Not a big deal but I figured I should point it out.

Hmmm, I made a mistake thanks for your report I will rename it

> Last thing. Where did you get this version of photoshop? Is hosted in dropbox but who made it? Is there anything special about it...

 this is a repack version, I used it because its installer has no any problem with wine or `dll` dependency. It's better than creative cloud installer

**Comment by LovelinMangang** [comment]
This package is missing Camera Raw filter I try to open it from **Edit >>Preferences >> Camera Raw** then error messages like this
![Screenshot from 2020-05-08 20-58-56](https://user-images.githubusercontent.com/56713851/81421671-734c5080-916f-11ea-92a7-0c4965558f41.png)

**Comment by AriaMoradi** [comment]
> I will add some argument for optional paths

what are the options? 
I couldn't find anything on readme

**Comment by AriaMoradi** [comment]
maybe adding a config.sh could work?

**Comment by Gictorbit** [comment]
I haven't added this feature yet. When I add this feature, I'll explain it in the `readme`

**Comment by AriaMoradi** [comment]
I think `.photoshopCCV19/launcher/launcher.sh` should undertake this changes:
* have the `$USER` variable calculated and hardcoded at the install time for portability reasons
* set `$SCR_PATH` relatively 
* rename `$SCR_PATH` to `$SRC_PATH` or even better `$BASE_PATH` or `$BASE_DIR`, anyways

**Comment by Gictorbit** [comment]
@NdranC @AriaMoradi 
I made some changes for a custom directory
you can use `-d` switch to specify installation path, and `-c` for the cache directory.
for example:
```bash
./PhotoshopSetupCustom.sh -d /mnt/myfiles/photoshop
or 
./PhotoshopSetup.sh -d /mnt/myfiles/photoshop -c /mnt/cache
```
if you don't use it, installer script uses the default path
also, uninstaller script and others will detect your custom path so there is no problem
I recommend just use `-d` argument and use default cache directory
try it and give me feedback

**Comment by NdranC** [comment]
That sounds great. I had one extra bit of feedback that might be related. I find very useful to have the winecfg.sh script saved somewhere. I usually put it inside the wine bottle, right next to the launcher.sh. Obviously it's pretty easy to manually copy it but my suggestion be to make this file and maybe some of the other useful scripts like the uninstall one inside the wine bottle by default. That way all the meaningful ways to interact with the current photoshop install are all in the same place without having to keep a permanent copy of the entire git repo.
