### ISSUE TITLE
Photoshop doesn't start/directly crashes

### ISSUE THREAD

**Issue by marc-sommer** [Gictorbit/photoshopCClinux#90]
**Describe the bug**

**linux Distribution (please complete the following information):**
 - Distro: Ubuntu 18.04.
 - Desktop Environment: Gnome
 - gpu: <pre><font color="#EF2929"><b>VGA</b></font> compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
</pre>
 - display server: 

**Additional context**

**Screenshots**

![image](https://user-images.githubusercontent.com/30161952/109998970-0e6f7180-7d12-11eb-82f0-d84395832139.png)

![image](https://user-images.githubusercontent.com/30161952/109999035-1af3ca00-7d12-11eb-8568-1a4e4cd731f4.png)

`0x000000007bc8e640 DbgBreakPoint in ntdll: int	$3
Modules:
Module	Address					Debug info	Name (202 modules)
PE	          240000-          284000	Deferred        tbb
PE	          290000-          37f000	Deferred        msvcr120
PE	          380000-          3c4000	Deferred        tbbmalloc
PE	          3d0000-          eea000	Deferred        svml_dispmd
PE	          ef0000-         1247000	Deferred        libmmd
PE	         1250000-         1292000	Deferred        crclient
PE	         12a0000-         1386000	Deferred        opencv_calib3d249
PE	         1390000-         1602000	Deferred        opencv_core249
PE	         1610000-         16b6000	Deferred        msvcp120
PE	         16c0000-         1764000	Deferred        opencv_flann249
PE	         1770000-         1a22000	Deferred        opencv_imgproc249
PE	         1a30000-         1b06000	Deferred        opencv_features2d249
PE	         1b10000-         1b7d000	Deferred        opencv_video249
PE	         1b80000-         1c8d000	Deferred        adobe_caps
PE	         1c90000-         1d0a000	Deferred        vulcancontrol
PE	         1d10000-         1daa000	Deferred        vulcanmessage5
PE	         1db0000-         1f1d000	Deferred        adobexmpfiles
PE	         1f20000-         205e000	Deferred        adobexmp
PE	         2060000-         20d5000	Deferred        cggl
PE	         20e0000-         214c000	Deferred        ahclient
PE	         2150000-         2167000	Deferred        amtlib
PE	         2170000-         267e000	Deferred        mps
PE	         2680000-         27e9000	Deferred        aide
PE	         27f0000-         2d6f000	Deferred        plugplugowl
PE	         2d70000-         2ffc000	Deferred        adobeowl
PE	         3000000-         31b0000	Deferred        adobelinguistic
PE	         31b0000-         31d9000	Deferred        citthreading
PE	         31e0000-         32a3000	Deferred        extendscript
PE	         32b0000-         3366000	Deferred        sccore
PE	         3370000-         33fc000	Deferred        manta
PE	        10000000-        100ee000	Deferred        axedomcore
PE	        16000000-        1600f000	Deferred        dnssd
PE	        4a800000-        4a93f000	Deferred        icucnv40
PE	        4ad00000-        4ba47000	Deferred        icudt40
PE	        6a000000-        6a964000	Deferred        cg
ELF	        7a800000-        7a9d2000	Deferred        opengl32<elf>
  \-PE	        7a850000-        7a9d2000	\               opengl32
ELF	        7b400000-        7b80d000	Dwarf           kernel32<elf>
  \-PE	        7b420000-        7b80d000	\               kernel32
ELF	        7bc00000-        7bd16000	Dwarf           ntdll<elf>
  \-PE	        7bc20000-        7bd16000	\               ntdll
ELF	        7c000000-        7c004000	Deferred        <wine-loader>
PE	       140000000-       14c94f000	Deferred        photoshop
PE	       180000000-       18012f000	Deferred        adbepm
ELF	    7f55a8f64000-    7f55a91b1000	Deferred        usp10<elf>
  \-PE	    7f55a8f70000-    7f55a91b1000	\               usp10
ELF	    7f55a91f7000-    7f55a9433000	Deferred        uxtheme<elf>
  \-PE	    7f55a9200000-    7f55a9433000	\               uxtheme
ELF	    7f55a9433000-    7f55a9639000	Deferred        libxfixes.so.3
ELF	    7f55a9639000-    7f55a9843000	Deferred        libxcursor.so.1
ELF	    7f55a9843000-    7f55a9a53000	Deferred        libxi.so.6
ELF	    7f55a9a53000-    7f55a9c56000	Deferred        libxcomposite.so.1
ELF	    7f55a9c56000-    7f55a9e61000	Deferred        libxrandr.so.2
ELF	    7f55a9e61000-    7f55aa06b000	Deferred        libxrender.so.1
ELF	    7f55aa06b000-    7f55aa271000	Deferred        libxxf86vm.so.1
ELF	    7f55aa271000-    7f55aa474000	Deferred        libxinerama.so.1
ELF	    7f55aa474000-    7f55aa689000	Deferred        libbsd.so.0
ELF	    7f55aa689000-    7f55aa88f000	Deferred        libxdmcp.so.6
ELF	    7f55aa88f000-    7f55aaa93000	Deferred        libxau.so.6
ELF	    7f55aaa93000-    7f55aacbb000	Deferred        libxcb.so.1
ELF	    7f55aacbb000-    7f55aaff3000	Deferred        libx11.so.6
ELF	    7f55aaff3000-    7f55ab205000	Deferred        libxext.so.6
ELF	    7f55ab205000-    7f55ab4a4000	Deferred        winex11<elf>
  \-PE	    7f55ab220000-    7f55ab4a4000	\               winex11
PE	    7f55ab4a4000-    7f55ab6b8000	Deferred        api-ms-win-core-localization-l1-
PE	    7f55ab4b0000-    7f55ab6b8000	Deferred        api-ms-win-core-localization-l1-C:\windows\system32\api-ms-win-core-localization-l1-2-1.dll
ELF	    7f55ab6b8000-    7f55ab8cb000	Deferred        api-ms-win-core-fibers-l1-1-1<el
PE	    7f55ab6c0000-    7f55ab8cb000	Deferred        api-ms-win-core-fibers-l1-1-1
ELF	    7f55ab8cb000-    7f55abadf000	Deferred        api-ms-win-core-synch-l1-2-0<elf
PE	    7f55ab8d0000-    7f55abadf000	Deferred        api-ms-win-core-synch-l1-2-0
ELF	    7f55abadf000-    7f55abcfe000	Deferred        concrt140<elf>
  \-PE	    7f55abaf0000-    7f55abcfe000	\               concrt140
ELF	    7f55abcfe000-    7f55abf13000	Deferred        libgpg-error.so.0
ELF	    7f55abf13000-    7f55ac22f000	Deferred        libgcrypt.so.20
ELF	    7f55ac22f000-    7f55ac44b000	Deferred        liblz4.so.1
ELF	    7f55ac44b000-    7f55ac671000	Deferred        liblzma.so.5
ELF	    7f55ac671000-    7f55ac879000	Deferred        librt.so.1
ELF	    7f55ac879000-    7f55acafd000	Deferred        libsystemd.so.0
ELF	    7f55acafd000-    7f55acd05000	Deferred        libffi.so.6
ELF	    7f55acd05000-    7f55acf1f000	Deferred        libresolv.so.2
ELF	    7f55acf1f000-    7f55ad123000	Deferred        libkeyutils.so.1
ELF	    7f55ad123000-    7f55ad370000	Deferred        libdbus-1.so.3
ELF	    7f55ad370000-    7f55ad5f1000	Deferred        libgmp.so.10
ELF	    7f55ad5f1000-    7f55ad825000	Deferred        libhogweed.so.4
ELF	    7f55ad825000-    7f55ada5b000	Deferred        libnettle.so.6
ELF	    7f55ada5b000-    7f55adc6e000	Deferred        libtasn1.so.6
ELF	    7f55adc6e000-    7f55adfec000	Deferred        libunistring.so.2
ELF	    7f55adfec000-    7f55ae209000	Deferred        libidn2.so.0
ELF	    7f55ae209000-    7f55ae538000	Deferred        libp11-kit.so.0
ELF	    7f55ae538000-    7f55ae743000	Deferred        libkrb5support.so.0
ELF	    7f55ae743000-    7f55ae947000	Deferred        libcom_err.so.2
ELF	    7f55ae947000-    7f55aeb79000	Deferred        libk5crypto.so.3
ELF	    7f55aeb79000-    7f55aee4f000	Deferred        libkrb5.so.3
ELF	    7f55aee4f000-    7f55af060000	Deferred        libavahi-client.so.3
ELF	    7f55af060000-    7f55af26c000	Deferred        libavahi-common.so.3
ELF	    7f55af26c000-    7f55af5d2000	Deferred        libgnutls.so.30
ELF	    7f55af5d2000-    7f55af81d000	Deferred        libgssapi_krb5.so.2
ELF	    7f55af81d000-    7f55afaa9000	Deferred        libcups.so.2
ELF	    7f55afac9000-    7f55afcef000	Deferred        imm32<elf>
  \-PE	    7f55afad0000-    7f55afcef000	\               imm32
ELF	    7f55afdda000-    7f55b000c000	Deferred        libexpat.so.1
ELF	    7f55b000c000-    7f55b0251000	Deferred        libfontconfig.so.1
ELF	    7f55b0251000-    7f55b0483000	Deferred        libpng16.so.16
ELF	    7f55b0483000-    7f55b0737000	Deferred        libfreetype.so.6
ELF	    7f55b0737000-    7f55b0a9f000	Deferred        wined3d<elf>
  \-PE	    7f55b0760000-    7f55b0a9f000	\               wined3d
ELF	    7f55b0a9f000-    7f55b0ccc000	Deferred        dxgi<elf>
  \-PE	    7f55b0ab0000-    7f55b0ccc000	\               dxgi
ELF	    7f55b0ccc000-    7f55b0f05000	Deferred        glu32<elf>
  \-PE	    7f55b0cd0000-    7f55b0f05000	\               glu32
ELF	    7f55b0f05000-    7f55b1119000	Deferred        api-ms-win-crt-conio-l1-1-0<elf>
  \-PE	    7f55b0f10000-    7f55b1119000	\               api-ms-win-crt-conio-l1-1-0
ELF	    7f55b1119000-    7f55b1330000	Deferred        api-ms-win-crt-multibyte-l1-1-0<
PE	    7f55b1120000-    7f55b1330000	Deferred        api-ms-win-crt-multibyte-l1-1-0
ELF	    7f55b1330000-    7f55b1614000	Deferred        crypt32<elf>
  \-PE	    7f55b1340000-    7f55b1614000	\               crypt32
ELF	    7f55b1614000-    7f55b182d000	Deferred        userenv<elf>
  \-PE	    7f55b1620000-    7f55b182d000	\               userenv
ELF	    7f55b182d000-    7f55b1a41000	Deferred        api-ms-win-crt-time-l1-1-0<elf>
  \-PE	    7f55b1830000-    7f55b1a41000	\               api-ms-win-crt-time-l1-1-0
ELF	    7f55b1a41000-    7f55b1c54000	Deferred        api-ms-win-crt-locale-l1-1-0<elf
PE	    7f55b1a50000-    7f55b1c54000	Deferred        api-ms-win-crt-locale-l1-1-0
ELF	    7f55b1c54000-    7f55b1e75000	Deferred        cabinet<elf>
  \-PE	    7f55b1c60000-    7f55b1e75000	\               cabinet
ELF	    7f55b1e75000-    7f55b21a6000	Deferred        comctl32<elf>
  \-PE	    7f55b1e80000-    7f55b21a6000	\               comctl32
ELF	    7f55b21a6000-    7f55b23d1000	Deferred        mpr<elf>
  \-PE	    7f55b21b0000-    7f55b23d1000	\               mpr
ELF	    7f55b23d1000-    7f55b2656000	Deferred        wininet<elf>
  \-PE	    7f55b23e0000-    7f55b2656000	\               wininet
ELF	    7f55b2656000-    7f55b2912000	Deferred        urlmon<elf>
  \-PE	    7f55b2670000-    7f55b2912000	\               urlmon
ELF	    7f55b2912000-    7f55b2c4f000	Deferred        msi<elf>
  \-PE	    7f55b2920000-    7f55b2c4f000	\               msi
ELF	    7f55b2c4f000-    7f55b2e64000	Deferred        api-ms-win-crt-convert-l1-1-0<el
PE	    7f55b2c60000-    7f55b2e64000	Deferred        api-ms-win-crt-convert-l1-1-0
PE	    7f55b2e64000-    7f55b3078000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	    7f55b2e70000-    7f55b3078000	Deferred        api-ms-win-crt-filesystem-l1-1-0C:\windows\system32\api-ms-win-crt-filesystem-l1-1-0.dll
ELF	    7f55b3078000-    7f55b3507000	Deferred        shell32<elf>
  \-PE	    7f55b3090000-    7f55b3507000	\               shell32
ELF	    7f55b3507000-    7f55b3724000	Deferred        libz.so.1
ELF	    7f55b3724000-    7f55b3993000	Deferred        dbghelp<elf>
  \-PE	    7f55b3730000-    7f55b3993000	\               dbghelp
ELF	    7f55b3993000-    7f55b3bac000	Deferred        api-ms-win-crt-math-l1-1-0<elf>
  \-PE	    7f55b39a0000-    7f55b3bac000	\               api-ms-win-crt-math-l1-1-0
ELF	    7f55b3bac000-    7f55b3dc0000	Deferred        api-ms-win-crt-utility-l1-1-0<el
PE	    7f55b3bb0000-    7f55b3dc0000	Deferred        api-ms-win-crt-utility-l1-1-0
PE	    7f55b3dc0000-    7f55b3fd3000	Deferred        api-ms-win-crt-environment-l1-1-
PE	    7f55b3dd0000-    7f55b3fd3000	Deferred        api-ms-win-crt-environment-l1-1-C:\windows\system32\api-ms-win-crt-environment-l1-1-0.dll
ELF	    7f55b3fd3000-    7f55b41e8000	Deferred        api-ms-win-crt-stdio-l1-1-0<elf>
  \-PE	    7f55b3fe0000-    7f55b41e8000	\               api-ms-win-crt-stdio-l1-1-0
ELF	    7f55b41e8000-    7f55b43fd000	Deferred        api-ms-win-crt-runtime-l1-1-0<el
PE	    7f55b41f0000-    7f55b43fd000	Deferred        api-ms-win-crt-runtime-l1-1-0
ELF	    7f55b43fd000-    7f55b4611000	Deferred        api-ms-win-crt-heap-l1-1-0<elf>
  \-PE	    7f55b4400000-    7f55b4611000	\               api-ms-win-crt-heap-l1-1-0
ELF	    7f55b4611000-    7f55b4827000	Deferred        api-ms-win-crt-string-l1-1-0<elf
PE	    7f55b4620000-    7f55b4827000	Deferred        api-ms-win-crt-string-l1-1-0
ELF	    7f55b4827000-    7f55b4a3d000	Deferred        vcruntime140<elf>
  \-PE	    7f55b4830000-    7f55b4a3d000	\               vcruntime140
ELF	    7f55b4a3d000-    7f55b4d51000	Dwarf           ucrtbase<elf>
  \-PE	    7f55b4a70000-    7f55b4d51000	\               ucrtbase
ELF	    7f55b4d51000-    7f55b508c000	Dwarf           msvcp140<elf>
  \-PE	    7f55b4d90000-    7f55b508c000	\               msvcp140
ELF	    7f55b508c000-    7f55b52d3000	Deferred        winspool<elf>
  \-PE	    7f55b5090000-    7f55b52d3000	\               winspool
ELF	    7f55b52d3000-    7f55b5651000	Deferred        oleaut32<elf>
  \-PE	    7f55b5300000-    7f55b5651000	\               oleaut32
ELF	    7f55b5651000-    7f55b586e000	Deferred        jsproxy<elf>
  \-PE	    7f55b5660000-    7f55b586e000	\               jsproxy
ELF	    7f55b586e000-    7f55b5ab0000	Deferred        winhttp<elf>
  \-PE	    7f55b5880000-    7f55b5ab0000	\               winhttp
ELF	    7f55b5ab0000-    7f55b5cf1000	Deferred        ws2_32<elf>
  \-PE	    7f55b5ac0000-    7f55b5cf1000	\               ws2_32
ELF	    7f55b5cf1000-    7f55b5f49000	Deferred        liblcms2.so.2
ELF	    7f55b5f49000-    7f55b616b000	Deferred        mscms<elf>
  \-PE	    7f55b5f50000-    7f55b616b000	\               mscms
ELF	    7f55b616b000-    7f55b6400000	Deferred        rpcrt4<elf>
  \-PE	    7f55b6180000-    7f55b6400000	\               rpcrt4
ELF	    7f55b6400000-    7f55b67a1000	Deferred        ole32<elf>
  \-PE	    7f55b6430000-    7f55b67a1000	\               ole32
ELF	    7f55b67a1000-    7f55b69bb000	Deferred        version<elf>
  \-PE	    7f55b67b0000-    7f55b69bb000	\               version
ELF	    7f55b69bb000-    7f55b6c4b000	Deferred        advapi32<elf>
  \-PE	    7f55b69d0000-    7f55b6c4b000	\               advapi32
ELF	    7f55b6c4b000-    7f55b6fc6000	Deferred        gdi32<elf>
  \-PE	    7f55b6c60000-    7f55b6fc6000	\               gdi32
ELF	    7f55b6fc6000-    7f55b7402000	Deferred        user32<elf>
  \-PE	    7f55b6ff0000-    7f55b7402000	\               user32
ELF	    7f55b7402000-    7f55b768f000	Deferred        shlwapi<elf>
  \-PE	    7f55b7410000-    7f55b768f000	\               shlwapi
ELF	    7f55b778f000-    7f55b7a42000	Deferred        gdiplus<elf>
  \-PE	    7f55b77a0000-    7f55b7a42000	\               gdiplus
ELF	    7f55b7b42000-    7f55b7d54000	Deferred        libnss_files.so.2
ELF	    7f55b7d54000-    7f55b7f6e000	Deferred        libnsl.so.1
ELF	    7f55b7f6e000-    7f55b817a000	Deferred        libnss_nis.so.2
ELF	    7f55b817a000-    7f55b8384000	Deferred        libnss_compat.so.2
ELF	    7f55b87ba000-    7f55b89d2000	Deferred        libgcc_s.so.1
ELF	    7f55b89d2000-    7f55b8d70000	Deferred        libm.so.6
ELF	    7f55b8d70000-    7f55b8f74000	Deferred        libdl.so.2
ELF	    7f55b8f74000-    7f55b9365000	Deferred        libc.so.6
ELF	    7f55b9365000-    7f55b9584000	Deferred        libpthread.so.0
ELF	    7f55b9929000-    7f55b9b55000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000025    0
	00000022    0
	0000001d    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	0000001c    0
	00000017    0
	00000016    0
	00000012    0
0000001a plugplay.exe
	0000001f    0
	0000001e    0
	0000001b    0
00000020 winedevice.exe
	0000002c    0
	00000024    0
	00000023    0
	00000021    0
00000028 explorer.exe
	0000002f    0
	0000002e    0
	0000002d    0
	00000029    0
0000002a (D) C:\users\user\PhotoshopSE\Photoshop.exe
	0000002b    0 <==
System information:
    Wine build: wine-3.0 (Ubuntu 3.0-1ubuntu1)
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 5.4.0-66-generic
`

**Comment by Gictorbit** [comment]
This is very similar to #89.

**Comment by Gictorbit** [comment]
please send me your log file and what version of wine do you have?

**Comment by marc-sommer** [comment]
@Gictorbit The wine version is as a matter of fact responsible for this. It was wine 3.0, just realized how old this is. Updated to 5.0 and it works fine. :+1:
