### ISSUE TITLE
Installer Script makes 32 Bit wine container instead of 64 Bit

### ISSUE THREAD

**Issue by samdisk11** [Gictorbit/photoshopCClinux#92]
**Describe the bug**
Installer creates a 32 Bit wine eviroment, but installs 64 Bit Photoshop and wont run after install.
if you run launcher.sh in a terminal you will get the following error from WINE:
64-bit application not supported in 32-bit prefix.

**linux Distribution (please complete the following information):**
 - Distro: Ubuntu 20.04 LTS x64 bit
 - Desktop Environment: [e.g. Gnome]
 - gpu: 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
 - display server: x11

**Additional context**
no additonal context needed???

**Screenshots**
screenshot of error is attached 
![image](https://user-images.githubusercontent.com/24478471/110197120-fcbfc400-7e0e-11eb-8efe-0f39851e1a60.png)

**Comment by Gictorbit** [comment]
the installer script creates a 64bit wine prefix not 32. just check your `drive_c` directory in your installation path and you will find `program Files` and `program Files x86` directories which means we use a 64bit prefix.

**Comment by samdisk11** [comment]
turns out that Ubuntu 20.04 LTS comes with a 32-bit version of wine preinstalled, i had to go get the 64 bit version from the wine website.

**Comment by adil192** [comment]
Uninstalling the default wine and reinstalling it from https://wiki.winehq.org/Ubuntu worked for me too on Pop!_OS 20.10
