### ISSUE TITLE
error: Cannot create photoshop command

### ISSUE THREAD

**Issue by jfontgd** [Gictorbit/photoshopCClinux#93]
I'm just new to linux.  any help ? 

 error message create /home/sam/.photoshopCCV19/launcher directory...
launcher.sh detected...
desktop entry detected...
create photoshop command...
Password: 
Sorry, try again.
Password: 
Sorry, try again.
Password: 
ln: failed to create symbolic link '/usr/local/bin/photoshop': No such file or directory 
sam@soluslinux ~/photoshopCClinux $ 
i tried a few times without mistyping my password and its still the same error

**Comment by Gictorbit** [comment]
hi can you give me the output of this command? 
```
ls /usr/local/bin/ 
```

**Comment by jfontgd** [comment]
its here:

sam@soluslinux ~ $ ls /usr/local/bin/
ls: cannot access '/usr/local/bin/': No such file or directory

im using solus linux btw...

**Comment by Gictorbit** [comment]
what about `ls /usr/bin` ?

**Comment by jfontgd** [comment]
here:

sam@soluslinux ~ $ ls /usr/bin
'['                                   lsb_release
 2to3                                 lscpu
 2to3-3.7                             lseopkg
 aa-easyprof                          lsipc
 aa-enabled                           lslocks
 aa-exec                              lslogins
 aafire                               lsmem
 aainfo                               lsns
 aalib-config                         lsof
 aasavefont                           lspci
 aatest                               lspisi
 abw2html                             lsusb
 abw2raw                              lsusb.py
 abw2text                             luajit
 aconnect                             luajit-2.0.5
 acyclic                              lv2bench
 addftinfo                            lv2info
 addmoddel                            lv2ls
 addr2line                            lvm-cache-stats
 affixcompress                        lz4
 afmtodit                             lz4c
 agentxtrap                           lz4cat
 alsabat                              lzcat
 alsa_in                              lzcmp
 alsaloop                             lzdiff
 alsamixer                            lzegrep
 alsa_out                             lzfgrep
 alsatplg                             lzgrep
 alsaucm                              lzip
 amidi                                lzless
 amixer                               lzma
 analyseplugin                        lzmadec
 analyze                              lzmainfo
 animate                              lzmore
 annotate                             machinectl
 any2djvu                             magick
 aomdec                               Magick++-config
 aomenc                               MagickCore-config
 aplay                                magick-script
 aplaymidi                            MagickWand-config
 applyplugin                          makealias
 appstream-builder                    makeconv
 appstream-compose                    makedb
 appstream-util                       man
 apropos                              mandb
 ar                                   manpath
 arecord                              man-recode
 arecordmidi                          mapscrn
 as                                   masktest
 aseqdump                             mbimcli
 aseqnet                              mbim-network
 aserver                              mcookie
 aulast                               md5sum
 aulastlog                            mdfind
 ausyscall                            media-ctl
 autopoint                            meinproc5
 auvirt                               mesg
 avahi-browse                         metacopy
 avahi-browse-domains                 metaflac
 avahi-publish                        mev
 avahi-publish-address                mib2c
 avahi-publish-service                mib2c-update
 avahi-resolve                        mid3cp
 avahi-resolve-address                mid3iconv
 avahi-resolve-host-name              mid3v2
 avahi-set-host-name                  mkbitmap
 awk                                  mk_cmds
 axfer                                mkfifo
 b2sum                                mkmodaliases
 baobab                               mksquashfs
 base32                               mm2gv
 base64                               mmcli
 basenc                               mmc-tool
 bashbug                              mmdblookup
 bc                                   mmroff
 bccmd                                modutil
 bcomps                               moggsplit
 bdftogd                              mogrify
 bd_info                              monitor-sensor
 bluemoon                             montage
 bluetoothctl                         mount
 bluetooth-sendto                     mouse-dpi-tool
 boltctl                              mouse-test
 bootctl                              mpicalc
 breeze-settings5                     mpris-proxy
 brotli                               mrwthumb
 btattach                             msgattrib
 btmon                                msgcat
 budgie-daemon                        msgcmp
 budgie-desktop                       msgcomm
 budgie-desktop-settings              msgconv
 budgie-panel                         msgen
 budgie-polkit-dialog                 msgexec
 budgie-run-dialog                    msgfilter
 budgie-wm                            msgfmt
 buildDocBookCatalog                  msggrep
 busctl                               msginit
 bwrap                                msgmerge
 bzz                                  msgunfmt
 c44                                  msguniq
 cabextract                           msidb
 cacaclock                            msiexec
 caca-config                          mtdev-test
 cacademo                             mtp-albumart
 cacafire                             mtp-albums
 cacaplay                             mtp-connect
 cacaserver                           mtp-delfile
 cacaview                             mtp-detect
 cal                                  mtp-emptyfolders
 canberra-boot                        mtp-files
 canberra-gtk-play                    mtp-filetree
 cancel                               mtp-folders
 captest                              mtp-format
 captoinfo                            mtp-getfile
 caribou-preferences                  mtp-getplaylist
 catchsegv                            mtp-hotplug
 catman                               mtp-newfolder
 cbc                                  mtp-newplaylist
 ccache-swig                          mtp-playlists
 ccomps                               mtp-reset
 cd-convert                           mtp-sendfile
 cd-create-profile                    mtp-sendtr
 cdda-player                          mtp-thumb
 cddb_query                           mtp-tracks
 cd-drive                             mtp-trexist
 cd-fix-profile                       mtrace
 cd-iccdump                           munch
 cd-info                              mutagen-inspect
 cd-it8                               mutagen-pony
 cd-paranoia                          mutter
 cdparanoia                           mvxattr
 cdr2raw                              mwaw2csv
 cdr2text                             mwaw2html
 cdr2xhtml                            mwaw2raw
 cd-read                              mwaw2svg
 cec-compliance                       mwaw2text
 cec-ctl                              mwawFile
 cec-follower                         mwawZip
 celtdec                              mypaint
 celtenc                              mypaint-ora-thumbnailer
 certutil                             namei
 c++filt                              nano
 chage                                nautilus
 chardetect                           nautilus-autorun-software
 chardetect3                          ncursesw5-config
 chattr                               ndptool
 chcon                                ndrdump
 checkbandwidth                       neato
 check-newconfigs.py                  neon-config
 checkXML5                            neqn
 chem                                 net
 chfn                                 netcap
 chmem                                net-snmp-cert
 chmorph                              net-snmp-config
 choom                                net-snmp-create-v3-user
 chroot                               newgidmap
 chrt                                 newgrp
 chsh                                 newuidmap
 chvt                                 nfs-cat
 cifsdd                               nfs-cp
 circo                                nfs-ls
 cisco-decrypt                        ngettext
 cjb2                                 nl
 cksum                                nm
 clear                                nm-applet
 clp                                  nmblookup
 clr-boot-manager                     nmcli
 clr-update-wrapper                   nm-connection-editor
 cluster                              nm-online
 cmis-client                          node
 cmx2raw                              nohup
 cmx2text                             nop
 cmx2xhtml                            notepad
 cngplp                               notify-send
 cnjatool                             npm
 code-oss                             nproc
 col                                  npx
 colcrt                               nroff
 colormgr                             nsenter
 colrm                                nslookup
 column                               nspr-config
 comar2to3                            nss-config
 comm                                 nsupdate
 compare                              ntfs-3g
 compile_et                           ntfs-3g.probe
 composite                            ntfscat
 conjure                              ntfscluster
 convert                              ntfscmp
 coredumpctl                          ntfsfix
 corelist                             ntfsinfo
 cpaldjvu                             ntfsls
 cpan                                 ntlm_auth
 createfp                             numbers2csv
 c_rehash                             numbers2raw
 csepdjvu                             numbers2text
 csplit                               numfmt
 cups-calibrate                       objcopy
 cupstestdsc                          objdump
 cupstestppd                          ociobakelut
 curl                                 ociocheck
 curl-config                          od
 cut                                  odbc_config
 cvt                                  odbcinst
 cvtsudoers                           oLschema2ldif
 cwebp                                onboard
 cx18-ctl                             onboard-settings
 cxpm                                 openconnect
 dav1d                                openssl
 dazzle-list-counters                 openssl-1.0
 db_archive                           openvt
 db_checkpoint                        opj_compress
 db_deadlock                          opj_decompress
 db_dump                              opj_dump
 db_hotbackup                         optipng
 db_load                              orca
 db_log_verify                        orcus-css-dump
 db_printlog                          orcus-csv
 db_recover                           orcus-detect
 db_replicate                         orcus-gnumeric
 db_stat                              orcus-json
 db_tuner                             orcus-mso-encryption
 db_upgrade                           orcus-ods
 dbus-binding-tool                    orcus-styles-ods
 dbus-cleanup-sockets                 orcus-xlsx
 dbus-daemon                          orcus-xls-xml
 dbus-launch                          orcus-xml
 dbus-monitor                         orcus-yaml
 dbus-run-session                     orcus-zip-dump
 dbus-send                            osage
 dbus-test-tool                       osinfo-detect
 dbus-update-activation-environment   osinfo-install-script
 dbus-uuidgen                         osinfo-query
 db_verify                            ostree
 dbwrap_tool                          p11-kit
 dc                                   pacat
 dc1394_reset_bus                     pacmd
 dconf                                pactl
 ddjvu                                padsp
 de265-acceleration_speed             pages2html
 de265-bjoentegaard                   pages2raw
 de265-block-rate-estim               pages2text
 de265-enc265                         pa-info
 de265-gen-enc-table                  pamon
 de265-rd-curves                      pango-list
 de265-tests                          pango-view
 de265-yuv-distortion                 paperconf
 deallocvt                            paplay
 decode_tm6000                        parec
 deflatehd                            parecord
 delaunay                             parsetrigrams
 delv                                 paste
 derb                                 pasuspender
 desktop-file-edit                    patchwork
 desktop-file-install                 pathchk
 desktop-file-validate                pax11publish
 desktoptojson                        pcap-config
 dhclient                             pcf2vpnc
 dhclient-script                      pcprofiledump
 dig                                  pcre-config
 dijkstra                             pcregrep
 dircolors                            pcretest
 dirmngr                              pdbedit
 dirmngr-client                       pdf2dsc
 dirname                              pdf2ps
 disable-paste                        pdfattach
 disktype                             pdfdetach
 display                              pdffonts
 display-buttons                      pdfimages
 display-coords                       pdfinfo
 djvm                                 pdfmom
 djvmcvt                              pdfroff
 djvudigital                          pdfseparate
 djvudump                             pdfsig
 djvuextract                          pdftocairo
 djvumake                             pdftohtml
 djvups                               pdftoppm
 djvused                              pdftops
 djvuserve                            pdftotext
 djvutoxml                            pdfunite
 djvutxt                              peas-demo
 djvuxmlparser                        peekfd
 dltest                               perl
 dnsdomainname                        perl5.32.1
 dnsmasq                              perlbug
 doflicky-ui                          perldoc
 dot                                  perlivp
 dot2gxl                              perlthanks
 dot_builtins                         pf2afm
 dotty                                pfbtopfa
 driverless                           pfbtops
 driverless-fax                       pic
 du                                   pic2graph
 dumpkeys                             piconv
 dumpmscat                            pinentry
 dumpsexp                             pinentry-curses
 dvb-fe-tool                          pinentry-gtk-2
 dvb-format-convert                   ping
 dvbv5-daemon                         ping6
 dvbv5-scan                           pinky
 dvbv5-zap                            pip3
 dvipdf                               pip3.7
 dwebp                                pipewire
 dwp                                  pipewire-media-session
 easy_install-3.7                     pipewire-pulse
 ebook2html                           pk12util
 ebook2raw                            pkaction
 ebook2text                           pkcheck
 edgepaint                            pk-example-frobnicate
 egrep                                pkexec
 eject                                pkgdata
 elfedit                              pkttyagent
 enc2xs                               pl2pm
 encguess                             plank
 enchant-2                            playout
 enchant-lsmod-2                      pldd
 encode_keychange                     plistutil
 env                                  pmd2raw
 envsubst                             pmd2svg
 eog                                  pmd2text
 eopkg                                pngfix
 eopkg-cli                            png-fix-itxt
 eps2eps                              pngtogd
 eqn                                  pngtogd2
 eqn2graph                            pod2html
 escputil                             pod2man
 esdcompat                            pod2text
 espeak                               pod2usage
 espeak-ng                            podchecker
 event_rpcgen.py                      portablectl
 evince                               post-grohtml
 evince-previewer                     potrace
 evince-thumbnailer                   ppdc
 exempi                               ppdhtml
 exifcomment                          ppdi
 exifdata                             ppdmerge
 exifprint                            ppdpo
 exifvalue                            pphs
 exiv2                                pr
 exiv2json                            preconv
 expand                               pre-grohtml
 expiry                               preparetips5
 expr                                 printafm
 exr2aces                             printenv
 exrenvmap                            printf
 exrheader                            prlimit
 exrmakepreview                       profiles
 exrmaketiled                         protoc
 exrmultipart                         protocoltojson
 exrmultiview                         prove
 exrstdattr                           proxy
 f2py                                 prtstat
 f2py2                                prune
 f2py2.7                              ps2ascii
 f2py3                                ps2epsi
 f2py3.7                              ps2pdf
 factor                               ps2pdf12
 faillog                              ps2pdf13
 fallocate                            ps2pdf14
 fc-cache                             ps2pdfwr
 fc-cat                               ps2ps
 fc-conflist                          ps2ps2
 fc-list                              pscap
 fc-match                             psfaddtable
 fc-pattern                           psfgettable
 fc-query                             psfstriptable
 fc-scan                              psfxtable
 fc-validate                          psicc
 fdp                                  psl
 ffmpeg                               pslog
 ffmpegthumbnailer                    pstree
 ffplay                               pstree.x11
 ffprobe                              ptar
 fftwf-wisdom                         ptardiff
 fftwl-wisdom                         ptargrep
 fftw-wisdom                          ptx
 fftw-wisdom-to-conf                  pub2raw
 fgconsole                            pub2xhtml
 fgrep                                pulseaudio
 fh2raw                               pw-cat
 fh2svg                               pw-cli
 fh2text                              pw-dot
 fido2-assert                         pw-dump
 fido2-cred                           pwmake
 fido2-token                          pw-metadata
 file                                 pw-mididump
 filecap                              pw-midiplay
 file-roller                          pw-midirecord
 fincore                              pw-mon
 find                                 pw-play
 findsmb                              pw-profiler
 firefox                              pw-record
 fixproc                              pw-reserve
 fix-qdf                              pwscore
 flac                                 pydoc
 flatpak                              pydoc3
 flatpak-bisect                       pydoc3.7
 flatpak-coredumpctl                  pygobject-codegen-2.0
 flock                                pylupdate5
 fluidsynth                           pyrcc5
 fmt                                  python
 fold                                 python2
 foomatic-combo-xml                   python2.7
 foomatic-compiledb                   python2.7-config
 foomatic-configure                   python2-config
 foomatic-datafile                    python2-pyuic5
 foomatic-perl-data                   python3
 foomatic-ppdfile                     python3.7
 foomatic-ppd-options                 python3.7-config
 foomatic-ppd-to-xml                  python3.7m
 foomatic-printjob                    python3.7m-config
 foomatic-rip                         python3-config
 foomatic-searchprinter               python-config
 fpcalc                               pyuic5
 ftp                                  pyvenv
 function_grep.pl                     pyvenv-3.7
 funzip                               qdbus
 fuser                                qmicli
 fusermount                           qmi-firmware-update
 gamma4scanimage                      qmi-network
 gapplication                         qml
 gawk                                 qmlcachegen
 gc                                   qmleasing
 gcab                                 qmlformat
 gcalccmd                             qmlimportscanner
 gcm-import                           qmllint
 gcm-inspect                          qmlmin
 gcm-picker                           qmlplugindump
 gcm-viewer                           qmlpreview
 gconf-merge-tree                     qmlprofiler
 gconftool-2                          qmlscene
 gcr-viewer                           qmltestrunner
 gd2copypal                           qmltyperegistrar
 gd2togif                             qpdf
 gd2topng                             qtpaths
 gdbm_dump                            qxp2raw
 gdbm_load                            qxp2svg
 gdbmtool                             qxp2text
 gdbus                                ranlib
 gdbus-codegen                        rcp
 gdcmpgif                             rctest
 gdialog                              rds-ctl
 gdiffmk                              readelf
 gdk-pixbuf-csource                   readlink
 gdk-pixbuf-pixdata                   realpath
 gdk-pixbuf-query-loaders             recode-sr-latin
 gdk-pixbuf-thumbnailer               refer
 gdmflexiserver                       regdiff
 gdm-screenshot                       regedit
 gdparttopng                          regpatch
 gdtopng                              regshell
 gedit                                regsvr32
 gegl                                 regtree
 gegl-imgcmp                          rename
 genbrk                               renice
 gencat                               reset
 gencfu                               resizecons
 gencnval                             resolvectl
 gendict                              rev
 genrb                                revdep-rebuild
 gentest                              rexec
 gentrigrams                          rhythmbox
 geotag                               rhythmbox-client
 geqn                                 rlogin
 getconf                              rnano
 getent                               roff2dvi
 getkeycodes                          roff2html
 getopt                               roff2pdf
 gettext                              roff2ps
 gettextize                           roff2text
 gettext.sh                           roff2x
 get-versions                         rofiles-fuse
 gif2rgb                              rpcclient
 gif2webp                             rpcgen
 gifbuild                             rsh
 gifclrmp                             rubberband
 gifecho                              runcon
 giffix                               s2tc_compress
 gifinto                              s2tc_decompress
 giftext                              s2tc_from_s3tc
 giftogd2                             sane-config
 giftool                              sane-find-scanner
 gio                                  sassc
 gio-querymodules                     sbcdec
 g-ir-annotation-tool                 sbcenc
 g-ir-compiler                        sbcinfo
 g-ir-generate                        scanimage
 g-ir-inspect                         sccmap
 g-ir-scanner                         sclient
 git                                  scmp_sys_resolver
 git-archive-all                      scour
 git-cvsserver                        scp
 gitk                                 scp-dbus-service
 git-receive-pack                     script
 git-shell                            scriptreplay
 git-upload-archive                   sdp-example
 git-upload-pack                      sdpscanner
 gjs                                  seahorse
 gjs-console                          secret-tool
 gkbd-keyboard-display                sed
 gl-driver-switch                     sensors
 glib-compile-resources               sensors-conf-convert
 glib-compile-schemas                 seq
 glib-genmarshal                      serdi
 glib-gettextize                      setarch
 glib-mkenums                         setfont
 glilypond                            setkeycodes
 glxgears                             setleds
 glxinfo                              setmetamode
 gml2gv                               setsid
 gnome-calculator                     setterm
 gnome-calendar                       setvtrgb
 gnome-control-center                 setxkbmap
 gnome-disk-image-mounter             sfdp
 gnome-disks                          sftp
 gnome-doc-prepare                    sg
 gnome-doc-tool                       sha1sum
 gnome-extensions                     sha224sum
 gnome-extensions-app                 sha256sum
 gnome-help                           sha384sum
 gnome-keyring                        sha512sum
 gnome-keyring-3                      shar
 gnome-keyring-daemon                 sharesec
 gnome-mpv                            shasum
 gnome-photos                         showconsolefont
 gnome-screensaver                    showkey
 gnome-screensaver-command            shred
 gnome-screenshot                     shuf
 gnome-session                        signtool
 gnome-session-custom-session         sim_client
 gnome-session-inhibit                simple-example
 gnome-session-quit                   sip
 gnome-shell                          sip3
 gnome-shell-extension-prefs          size
 gnome-shell-extension-tool           slencheck
 gnome-shell-perf-tool                smbcacls
 gnome-system-monitor                 smbclient
 gnome-terminal                       smbcontrol
 gobject-query                        smbcquotas
 google-chrome-stable                 smbget
 gparted                              smbpasswd
 gpasswd                              smbspool
 gpcl6                                smbstatus
 gperl                                smbtar
 gpg                                  smbtree
 gpg2                                 smtpd.py
 gpg-agent                            snap
 gpgconf                              snapctl
 gpg-connect-agent                    sndfile-cmp
 gpg-error                            sndfile-concat
 gpg-error-config                     sndfile-convert
 gpgme-config                         sndfile-deinterleave
 gpgme-json                           sndfile-info
 gpgme-tool                           sndfile-interleave
 gpgparsemail                         sndfile-metadata-get
 gpgrt-config                         sndfile-metadata-set
 gpgscm                               sndfile-play
 gpgsm                                sndfile-resample
 gpgsplit                             sndfile-salvage
 gpgtar                               snmp-bridge-mib
 gpgv                                 snmpbulkget
 gpg-wks-server                       snmpbulkwalk
 gphoto2-config                       snmpcheck
 gphoto2-port-config                  snmpconf
 gpinyin                              snmpdelta
 gpm-root                             snmpdf
 gprof                                snmpget
 gr2fonttest                          snmpgetnext
 grap2graph                           snmpinform
 graphml2gv                           snmpnetstat
 grep                                 snmpping
 gresource                            snmpps
 grilo-test-ui-0.3                    snmpset
 grl-inspect-0.3                      snmpstatus
 grl-launch-0.3                       snmptable
 grn                                  snmptest
 grodvi                               snmptop
 groff                                snmptranslate
 groffer                              snmptrap
 grog                                 snmpusm
 grolbp                               snmpvacm
 grolj4                               snmpwalk
 gropdf                               soelim
 grops                                soffice
 grotty                               solid-hardware5
 groups                               solus-sc
 gs                                   solus-update-checker
 gsbj                                 sordi
 gsc                                  sord_validate
 gsdj                                 sotruss
 gsdj500                              soundstretch
 gsettings                            spa-acp-tool
 gsettings-data-convert               spa-inspect
 gsettings-schema-convert             spa-monitor
 gsf                                  spa-resample
 gsf-office-thumbnailer               spd-conf
 gsf-vba-dump                         spd-say
 gsl-config                           spdsend
 gsl-histogram                        speak
 gslj                                 speaker-test
 gslp                                 speak-ng
 gsl-randist                          speech-dispatcher
 gsnd                                 speexdec
 gsound-play                          speexenc
 gspell-app1                          spellout
 gss-client                           spice-vdagent
 gst-device-monitor-1.0               splain
 gst-discoverer-1.0                   split
 gst-inspect-1.0                      sprof
 gst-launch-1.0                       sqlite3
 gst-play-1.0                         sqlite3_analyzer
 gst-stats-1.0                        srt-ffplay
 gst-tester-1.0                       ssh
 gst-transcoder-1.0                   ssh-add
 gst-typefind-1.0                     ssh-agent
 gsx                                  ssh-copy-id
 gtbl                                 ssh-keygen
 gtester                              ssh-keyscan
 gtester-report                       ssltap
 gtf                                  start-pulseaudio-x11
 gtk-builder-convert                  startx
 gtk-builder-tool                     stat
 gtk-encode-symbolic-svg              stdbuf
 gtk-launch                           stl2gts
 gtk-query-immodules-2.0              stoken
 gtk-query-immodules-3.0              stream
 gtk-query-settings                   streamzip
 gtk-update-icon-cache                strings
 gtk-update-icon-cache-2.0            strip
 gtk-update-icon-cache-3.0            stunbdc
 gts2dxf                              stund
 gts2oogl                             substrings.pl
 gts2stl                              sudo
 gtscheck                             sudoedit
 gtscompare                           sudoreplay
 gts-config                           sum
 gtstemplate                          swig
 gunzip                               system-config-printer
 gusbcmd                              system-config-printer-applet
 gv2gml                               systemctl
 gv2gxl                               systemd-analyze
 gvcolor                              systemd-ask-password
 gvedit                               systemd-cat
 gvgen                                systemd-cgls
 gvmap                                systemd-cgtop
 gvmap.sh                             systemd-delta
 gvpack                               systemd-detect-virt
 gvpr                                 systemd-escape
 gxl2dot                              systemd-firstboot
 gxl2gv                               systemd-hwdb
 gxps                                 systemd-id128
 gzexe                                systemd-inhibit
 gzip                                 systemd-machine-id-setup
 h2ph                                 systemd-mount
 h2xs                                 systemd-notify
 hav                                  systemd-nspawn
 hb-ot-shape-closure                  systemd-path
 hb-shape                             systemd-resolve
 hb-subset                            systemd-run
 head                                 systemd-socket-activate
 heif-convert                         systemd-stdio-bridge
 heif-enc                             systemd-sysusers
 heif-info                            systemd-tmpfiles
 heif-thumbnailer                     systemd-tty-ask-password-agent
 hex2hcd                              systemd-umount
 hexchat                              tabs
 hexdump                              tac
 hltest                               taglib-config
 hmac256                              taglist
 host                                 tail
 hostid                               talk
 hostname                             taskset
 hostnamectl                          tbl
 hpftodit                             tclsh
 hunspell                             tclsh8.6
 hunzip                               tee
 hzip                                 telnet
 i386                                 test
 ibus                                 testparm
 ibus-daemon                          testpattern
 ibus-setup                           tfmtodit
 iconv                                tftp
 icu-config                           th_gen_idx.pl
 icuinfo                              threaded-example
 id                                   thunderbird
 identify                             tic
 idevicebackup                        time
 idevicebackup2                       timedatectl
 idevicecrashreport                   timeout
 idevicedate                          tkmib
 idevicedebug                         toe
 idevicedebugserverproxy              touchpad-edge-detector
 idevicediagnostics                   tput
 ideviceenterrecovery                 tr
 idevice_id                           traceroute
 ideviceimagemounter                  tracker3
 ideviceinfo                          transform
 idevicename                          transicc
 idevicenotificationproxy             traptoemail
 idevicepair                          tred
 ideviceprovision                     tree
 idevicescreenshot                    troff
 idevicesetlocation                   truncate
 idevicesyslog                        trust
 idle                                 tset
 idle3                                tsort
 idle3.7                              ttfread
 idn2                                 tty
 iecset                               twolame
 ifconfig                             twopi
 img2txt                              tzselect
 img2webp                             uchardet
 imgcmp                               uconv
 imginfo                              udevadm
 imlib2_bumpmap                       udisksctl
 imlib2_colorspace                    ul
 imlib2-config                        ulockmgr_server
 imlib2_conv                          umax_pp
 imlib2_grab                          umount
 imlib2_load                          uname26
 imlib2_poly                          uncompress
 imlib2_show                          uneopkg
 imlib2_test                          unexpand
 imlib2_view                          unflatten
 import                               unicode_start
 indxbib                              unicode_stop
 inetcat                              uniq
 inflatehd                            unix-lpr.sh
 infocmp                              unlz4
 infotocap                            unlzma
 inkscape                             unmunch
 inkview                              unopkg
 inotifywait                          unpisi
 inotifywatch                         unrar
 install                              unshar
 install-printerdriver                unshare
 instmodsh                            unsquashfs
 inxi                                 unxz
 ionice                               unzip
 ipcmk                                unzipsfx
 ipcrm                                unzstd
 ipcs                                 updatedb
 ipf-mod.pl                           update-desktop-database
 ipod-read-sysinfo-extended           update-mime-database
 ippfind                              upower
 ipptool                              urlgrabber
 iproxy                               usb-devices
 iptables-xml                         usbhid-dump
 iptc                                 users
 iptceasy                             us.getsol.budgie-desktop-view
 iptcprint                            utmpdump
 ir-ctl                               uuclient
 ir-keytable                          uudecode
 isdv4-serial-debugger                uuencode
 isdv4-serial-inputattach             uuidgen
 iso-info                             uuidparse
 iso-read                             v4l2-compliance
 isosize                              v4l2-ctl
 ispellaff2myspell                    v4l2-sysfs-path
 isql                                 vamp-rdf-template-generator
 iusql                                vamp-simple-host
 ivtv-ctl                             vimdot
 ixion-formula-tokenizer              vkd3d-compiler
 ixion-parser                         vlock
 ixion-sorter                         voikkogc
 jack_alias                           voikkohyphenate
 jack_bufsize                         voikkospell
 jack_connect                         voikkovfstc
 jack_control                         volume_key
 jack_cpu                             vpnc
 jack_cpu_load                        vpnc-disconnect
 jackd                                vpxdec
 jackdbus                             vpxenc
 jack_disconnect                      vsd2raw
 jack_evmon                           vsd2text
 jack_freewheel                       vsd2xhtml
 jack_iodelay                         vspipe
 jack_latent_client                   vss2raw
 jack_load                            vss2text
 jack_lsp                             vss2xhtml
 jack_metro                           vte-2.91
 jack_midi_dump                       vwebp
 jack_midi_latency_test               wall
 jack_midiseq                         watchgnupg
 jack_midisine                        wbinfo
 jack_monitor_client                  wc
 jack_multiple_metro                  WebKitWebDriver
 jack_net_master                      webpinfo
 jack_net_slave                       webpmux
 jack_netsource                       webpng
 jack_property                        wget
 jack_rec                             whatis
 jack_samplerate                      whereis
 jack_server_control                  which
 jack_session_notify                  who
 jack_showtime                        whoami
 jack_simdtests                       widl
 jack_simple_client                   wine
 jack_simple_session_client           wine64
 jack_test                            wine64-preloader
 jack_thru                            wineboot
 jack_transport                       winebuild
 jack_unload                          winecfg
 jack_wait                            wineconsole
 jack_zombie                          winecpp
 jasper                               winedbg
 jbig2dec                             winedump
 jiv                                  winefile
 join                                 wineg++
 journalctl                           winegcc
 js38                                 winemaker
 js38-config                          winemine
 js78                                 winepath
 js78-config                          wine-preloader
 json-glib-format                     wineserver
 json-glib-validate                   winetricks
 json_pp                              wish
 k5srvutil                            wish8.6
 kadmin                               wks2csv
 kbdinfo                              wks2raw
 kbd_mode                             wks2text
 kbdrate                              wmc
 kbuildsycoca5                        wnckprop
 kbxutil                              wnck-urgency-monitor
 kcookiejar5                          woff2_compress
 kded5                                woff2_decompress
 kdestroy                             woff2_info
 key2raw                              wordforms
 key2text                             wordlist2hunspell
 key2xhtml                            wpd2html
 kglobalaccel5                        wpd2raw
 kiconfinder5                         wpd2text
 killall                              wpg2raw
 kinit                                wpg2svg
 klist                                wpg2svgbatch.pl
 knewstuff-dialog                     wps2html
 kpackagelauncherqml                  wps2raw
 kpackagetool5                        wps2text
 kpasswd                              wrc
 kquitapp5                            wsdd
 krb5-config                          X
 kreadconfig5                         x264
 krita                                x265
 kritarunner                          x86_64
 krita_version                        xargs
 ksu                                  xauth
 kswitch                              xdg-dbus-proxy
 ktelnetservice5                      xdg-desktop-icon
 ktrash5                              xdg-desktop-menu
 ktutil                               xdg-email
 kvno                                 xdg-icon-resource
 kwalletd5                            xdg-mime
 kwallet-query                        xdg-open
 kwriteconfig5                        xdg-screensaver
 l2ping                               xdg-settings
 l2test                               xdg-user-dir
 lame                                 xdg-user-dirs-gtk-update
 lash_control                         xdg-user-dirs-update
 lashd                                xdpyinfo
 lash_panel                           Xephyr
 lash_save_button                     xgettext
 lash_simple_client                   xhost
 lash_synth                           xinit
 last                                 xkbcomp
 lastb                                xkeystone
 lastlog                              xml2-config
 ld                                   xml2po
 ldapadd                              xmlcatalog
 ldapcompare                          xml_grep
 ldapdelete                           xmllint
 ldapexop                             xml_merge
 ldapmodify                           xmlpatterns
 ldapmodrdn                           xmlpatternsvalidator
 ldappasswd                           xml_pp
 ldapsearch                           xmlsec1
 ldapurl                              xml_spellcheck
 ldapwhoami                           xml_split
 ldbadd                               xmlwf
 ldbdel                               xmodmap
 ldbedit                              xmpdump
 ld.bfd                               xmpparse
 ldbmodify                            xmpprint
 ldbrename                            xmpsample
 ldbsearch                            Xnest
 ldd                                  Xorg
 lddlibc4                             xpstojpeg
 ldm-session-init                     xpstopdf
 lefty                                xpstopng
 less                                 xpstops
 lessecho                             xpstosvg
 lesskey                              xrandr
 lexgrog                              xset
 libassuan-config                     xsetwacom
 libevdev-tweak-device                xsltproc
 libgcrypt-config                     xsubpp
 libglade-convert                     x-terminal-emulator
 libgtop_daemon2                      xtrace
 libgtop_server2                      Xwayland
 libieee1284_test                     xz
 libinput                             xzcat
 libnetcfg                            xzcmp
 libreoffice                          xzdec
 libwacom-list-local-devices          xzdiff
 lilv-bench                           xzegrep
 linkicc                              xzfgrep
 linux32                              xzgrep
 linux64                              xzless
 linux-driver-management              xzmore
 listplugins                          yat2m
 lkbib                                yelp
 lneato                               yes
 loadkeys                             youtube-dl
 loadunimap                           yt-dlc
 localc                               zcat
 locale                               zcmp
 localectl                            zdiff
 localedef                            zegrep
 locate                               zenity
 locktest                             zfgrep
 lodraw                               zforce
 loffice                              zgrep
 lofromtemplate                       zip
 logger                               zipcloak
 loginctl                             zipdetails
 logname                              zipgrep
 loimpress                            zipinfo
 look                                 zipnote
 lookbib                              zipsplit
 loweb                                zless
 lowntfs-3g                           zlib-flate
 lowriter                             zmf2raw
 lp                                   zmf2svg
 lpoptions                            zmore
 lpq                                  znew
 lpr                                  zstd
 lprm                                 zstdcat
 lprsetup.sh                          zstdgrep
 lpstat                               zstdless
 lsattr                               zstdmt
sam@soluslinux ~ $

**Comment by Gictorbit** [comment]
ok seems you don't have `/usr/local/bin` so I will modify the installer script to solve this problem thank you

**Comment by jfontgd** [comment]
Wow okay thankyou so much! I very much appreciate it! I'll be waitinggg !

**Comment by Gictorbit** [comment]
also there is a temporary solution, you can make `/usr/local/bin` directory and reinstall photoshop I think it could solve the problem

**Comment by jfontgd** [comment]
okay i will try that nowww

**Comment by Gictorbit** [comment]
Pardon me I have another question can you send me the output of `echo $PATH`?

**Comment by jfontgd** [comment]
im trying to reinstall now..
yes here it is :
sam@soluslinux ~/photoshopCClinux $ echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/snap/bin
sam@soluslinux ~/photoshopCClinux $

**Comment by jfontgd** [comment]
or you need me to check that after reinstalling this? il check again after i finish this

**Comment by Gictorbit** [comment]
No, I got what I needed, I will fix this issue and tell you the result thanks

**Comment by jfontgd** [comment]
it worked!!! Thou i had two errors when i opened it... thats great! il just wait for that..
in case you might want to see the error 
![157533070_472778564102780_3598155170622528245_n](https://user-images.githubusercontent.com/75028626/110203968-b4a2af00-7eab-11eb-8efb-149079066d5f.jpg)
![157566072_252713876433060_1974293625004125084_n](https://user-images.githubusercontent.com/75028626/110203972-b66c7280-7eab-11eb-8bb5-453194202975.jpg)

**Comment by jfontgd** [comment]
additional info : this error appeared when i tried to open a new file doc but after clicking okay it still opened a new file went to try brushes and it was all okay. until i tried liquify thats when it crahsed 
![157522590_1347212835634746_6234798781176996743_n](https://user-images.githubusercontent.com/75028626/110204910-88d5f800-7eb0-11eb-8a05-a8e628daa19c.jpg)

**Comment by Gictorbit** [comment]
I read your comment and these errors are not related to this issue so I had to delete them sorry
these kinds of errors related to photoshop executable binary file and I have not any solution for this warnings yet, you can ignore warnings, they appear just when you run photoshop first time and program will work as well

**Comment by jfontgd** [comment]
oh okay i get it .. its fine. il just wait for the update

**Comment by Gictorbit** [comment]
I modified the installer script. Problem solved
