### ISSUE TITLE
Photoshop doesn't open: wine: failed to load start.exe: 40000003

### ISSUE THREAD

**Issue by jadc** [Gictorbit/photoshopCClinux#97]
This isn't an issue with photoshopCClinux, but I thought I'd post it here to help others.

There is a recent bug with wine-staging that causes Photoshop to not open. Rather, it throws the error `wine: failed to load start.exe: 40000003`. 

To fix this for the time being,
* Edit /usr/local/bin/photoshop
* Change "wine" in the last line to "wine64"

**Comment by Gictorbit** [comment]
thanks I will fix this
